IngressBytesAgg >= 0
IngressBytesAgg <= 77967358
InRxmitBytesAgg <= (InCongestionBytesAgg + IngressBytesAgg)
InCongestionBytesAgg <= (IngressBytesAgg + OutRxmitBytesAgg)
InCongestionBytesAgg <= 77967358
InCongestionBytesAgg >= 0
InRxmitBytesAgg <= (IngressBytesAgg + OutRxmitBytesAgg)
InCongestionBytesAgg <= (EgressBytesAgg + IngressBytesAgg)
InRxmitBytesAgg >= 0
OutRxmitBytesAgg <= (EgressBytesAgg + InCongestionBytesAgg)
InRxmitBytesAgg <= 16311209
InRxmitBytesAgg <= (EgressBytesAgg + IngressBytesAgg)
OutRxmitBytesAgg >= 0
EgressBytesAgg >= 0
OutRxmitBytesAgg <= (EgressBytesAgg + InRxmitBytesAgg)
InCongestionBytesAgg <= (InRxmitBytesAgg + IngressBytesAgg)
OutRxmitBytesAgg <= (EgressBytesAgg + IngressBytesAgg)
OutRxmitBytesAgg <= 18519203
EgressBytesAgg <= 144238585
ConnectionsAgg >= 0
ConnectionsAgg <= 26796
