SrcIpAddr != private_broadcast
(DstPt = 138) -> ((DstIpAddr = private_broadcast) AND (Flags = noflags) AND (Proto = UDP) AND (SrcIpAddr = private_p2p) AND (SrcPt = 138))
((DstIpAddr = private_p2p) AND (DstPt = 123)) -> (SrcIpAddr = public_p2p)
(DstIpAddr = private_broadcast) -> ((Flags = noflags) AND (Proto = UDP))
(SrcPt = 53) -> ((DstIpAddr = private_p2p) AND (DstPt = unknown_port) AND (SrcIpAddr = dns))
((DstIpAddr = dns) AND (Proto = ICMP)) -> (DstPt = 3)
((DstIpAddr = private_p2p) AND (SrcPt = 0)) -> (Proto = ICMP)
Proto <= 3
(SrcPt = 445) -> ((DstIpAddr = private_p2p) AND (DstPt = unknown_port) AND (Flags = hasflags) AND (Proto = TCP) AND (SrcIpAddr = private_p2p))
(DstPt = 123) -> ((Flags = noflags) AND (Proto = UDP) AND (SrcPt = 123))
(SrcPt = 0) -> (Flags = noflags)
(DstPt = 68) -> ((Flags = noflags) AND (Proto = UDP) AND (SrcIpAddr = private_p2p) AND (SrcPt = 67))
(SrcPt = 8080) -> ((DstIpAddr = private_p2p) AND (DstPt = unknown_port) AND (Flags = hasflags) AND (Proto = TCP) AND (SrcIpAddr = public_p2p))
(DstPt = 11) -> ((DstIpAddr = private_p2p) AND (Flags = noflags) AND (Proto = ICMP) AND (SrcIpAddr = public_p2p) AND (SrcPt = 0))
((Flags = noflags) AND (SrcPt = 53)) -> (Proto = UDP)
(Proto = TCP) -> (Flags = hasflags)
((DstIpAddr = public_p2p) AND (Proto = UDP) AND (SrcPt = unknown_port)) -> (DstPt = unknown_port)
((Flags = noflags) AND (SrcIpAddr = dns)) -> (Proto = UDP)
(SrcIpAddr = public_p2p) -> (DstIpAddr = private_p2p)
((DstIpAddr = public_p2p) AND (DstPt = unknown_port)) -> (SrcPt = unknown_port)
(SrcPt = 8082) -> ((DstIpAddr = private_p2p) AND (DstPt = unknown_port) AND (Flags = hasflags) AND (Proto = TCP) AND (SrcIpAddr = public_p2p))
(DstPt = 8000) -> ((DstIpAddr = public_p2p) AND (Flags = hasflags) AND (Proto = TCP) AND (SrcIpAddr = private_p2p) AND (SrcPt = unknown_port))
(DstPt = 25) -> ((DstIpAddr = public_p2p) AND (Flags = hasflags) AND (Proto = TCP) AND (SrcIpAddr = private_p2p) AND (SrcPt = unknown_port))
SrcPt <= 60000
((DstPt = 53) AND (Flags = noflags)) -> (Proto = UDP)
(SrcPt = 123) -> ((DstPt = 123) AND (Flags = noflags) AND (Proto = UDP))
(DstPt = 80) -> ((Flags = hasflags) AND (Proto = TCP) AND (SrcIpAddr = private_p2p) AND (SrcPt = unknown_port))
DstIpAddr >= 0
((DstIpAddr = private_p2p) AND (SrcPt = 68)) -> (SrcIpAddr = private_p2p)
((Proto = TCP) AND (SrcIpAddr = public_p2p)) -> (DstPt = unknown_port)
((DstIpAddr = dns) AND (SrcPt = unknown_port)) -> (DstPt = 53)
Proto >= 0
(SrcPt = 8000) -> ((DstIpAddr = private_p2p) AND (DstPt = unknown_port) AND (Flags = hasflags) AND (Proto = TCP) AND (SrcIpAddr = public_p2p))
(DstIpAddr = dns) -> (SrcIpAddr = private_p2p)
(DstPt = 8080) -> ((DstIpAddr = public_p2p) AND (Flags = hasflags) AND (Proto = TCP) AND (SrcIpAddr = private_p2p) AND (SrcPt = unknown_port))
Flags >= 0
DstIpAddr != 0.0.0.0
((SrcIpAddr = private_p2p) AND (SrcPt = 123)) -> (DstIpAddr = public_p2p)
(SrcPt = 138) -> ((DstIpAddr = private_broadcast) AND (DstPt = 138) AND (Flags = noflags) AND (Proto = UDP) AND (SrcIpAddr = private_p2p))
((DstIpAddr = private_p2p) AND (SrcIpAddr = private_p2p) AND (SrcPt = 0)) -> (DstPt = 3)
((DstIpAddr = private_broadcast) AND (DstPt = unknown_port)) -> ((SrcIpAddr = private_p2p) AND (SrcPt = unknown_port))
(Proto = UDP) -> (Flags = noflags)
((DstPt = 123) AND (SrcIpAddr = private_p2p)) -> (DstIpAddr = public_p2p)
SrcIpAddr <= 4
(DstPt = 3) -> ((Flags = noflags) AND (Proto = ICMP) AND (SrcPt = 0))
((DstIpAddr = private_broadcast) AND (SrcPt = unknown_port)) -> ((DstPt = unknown_port) AND (SrcIpAddr = private_p2p))
((DstIpAddr = public_p2p) AND (Flags = noflags) AND (SrcPt = unknown_port)) -> (DstPt = unknown_port)
(DstPt = 22) -> ((Flags = hasflags) AND (Proto = TCP) AND (SrcIpAddr = private_p2p) AND (SrcPt = unknown_port))
DstIpAddr <= 4
(Flags = hasflags) -> (Proto = TCP)
(DstPt = 137) -> ((DstIpAddr = private_broadcast) AND (Flags = noflags) AND (Proto = UDP) AND (SrcIpAddr = private_p2p) AND (SrcPt = 137))
((DstIpAddr = private_p2p) AND (DstPt = unknown_port) AND (SrcIpAddr = private_p2p)) -> ((Flags = hasflags) AND (Proto = TCP))
((DstPt = unknown_port) AND (Proto = UDP) AND (SrcIpAddr = private_p2p)) -> (SrcPt = unknown_port)
((DstPt = unknown_port) AND (Flags = noflags) AND (SrcIpAddr = private_p2p)) -> (SrcPt = unknown_port)
((DstIpAddr = private_p2p) AND (Proto = ICMP) AND (SrcIpAddr = private_p2p)) -> (DstPt = 3)
(DstPt = 993) -> ((DstIpAddr = private_p2p) AND (Flags = hasflags) AND (Proto = TCP) AND (SrcIpAddr = private_p2p) AND (SrcPt = unknown_port))
(DstPt = 0) -> ((DstIpAddr = public_p2p) AND (Flags = noflags) AND (Proto = IGMP) AND (SrcIpAddr = private_p2p) AND (SrcPt = 0))
((DstIpAddr = public_p2p) AND (Proto = TCP)) -> (SrcPt = unknown_port)
(DstIpAddr = public_p2p) -> (SrcIpAddr = private_p2p)
((SrcIpAddr = public_p2p) AND (SrcPt = 0)) -> (Proto = ICMP)
((DstIpAddr = dns) AND (SrcPt = 0)) -> ((DstPt = 3) AND (Proto = ICMP))
((DstIpAddr = private_p2p) AND (SrcIpAddr = private_p2p) AND (SrcPt = unknown_port)) -> ((Flags = hasflags) AND (Proto = TCP))
SrcPt >= 0
(Proto = IGMP) -> ((DstIpAddr = public_p2p) AND (DstPt = 0) AND (Flags = noflags) AND (SrcIpAddr = private_p2p) AND (SrcPt = 0))
((Flags = hasflags) AND (SrcIpAddr = public_p2p)) -> (DstPt = unknown_port)
(SrcPt = 67) -> ((DstPt = 68) AND (Flags = noflags) AND (Proto = UDP) AND (SrcIpAddr = private_p2p))
(Proto = ICMP) -> ((Flags = noflags) AND (SrcPt = 0))
(DstPt = 8) -> ((DstIpAddr = public_p2p) AND (Flags = noflags) AND (Proto = ICMP) AND (SrcIpAddr = private_p2p) AND (SrcPt = 0))
(SrcPt = 993) -> ((DstIpAddr = private_p2p) AND (DstPt = unknown_port) AND (Flags = hasflags) AND (Proto = TCP) AND (SrcIpAddr = private_p2p))
(SrcPt = 587) -> ((DstIpAddr = private_p2p) AND (DstPt = unknown_port) AND (Flags = hasflags) AND (Proto = TCP) AND (SrcIpAddr = private_p2p))
(SrcPt = 80) -> ((DstIpAddr = private_p2p) AND (DstPt = unknown_port) AND (Flags = hasflags) AND (Proto = TCP))
DstPt <= 60000
((DstIpAddr = private_p2p) AND (DstPt = 67)) -> (SrcIpAddr = private_p2p)
(DstPt = 5353) -> ((DstIpAddr = public_p2p) AND (Flags = noflags) AND (Proto = UDP) AND (SrcIpAddr = private_p2p) AND (SrcPt = 5353))
(DstPt = 67) -> ((Flags = noflags) AND (Proto = UDP) AND (SrcPt = 68))
((SrcIpAddr = public_p2p) AND (SrcPt = unknown_port)) -> (DstPt = unknown_port)
((DstPt = unknown_port) AND (Flags = noflags)) -> (Proto = UDP)
(DstPt = 53) -> ((DstIpAddr = dns) AND (SrcIpAddr = private_p2p) AND (SrcPt = unknown_port))
(SrcPt = 443) -> ((DstIpAddr = private_p2p) AND (DstPt = unknown_port) AND (Flags = hasflags) AND (Proto = TCP) AND (SrcIpAddr = public_p2p))
((DstPt = unknown_port) AND (Proto = UDP) AND (SrcIpAddr = public_p2p)) -> (SrcPt = unknown_port)
(SrcPt = 5353) -> ((DstIpAddr = public_p2p) AND (DstPt = 5353) AND (Flags = noflags) AND (Proto = UDP) AND (SrcIpAddr = private_p2p))
SrcIpAddr >= 0
(SrcPt = 137) -> ((DstIpAddr = private_broadcast) AND (DstPt = 137) AND (Flags = noflags) AND (Proto = UDP) AND (SrcIpAddr = private_p2p))
((DstIpAddr = dns) AND (Proto = TCP)) -> ((DstPt = 53) AND (SrcPt = unknown_port))
(SrcIpAddr = 0.0.0.0) -> ((DstIpAddr = private_broadcast) AND (DstPt = 67) AND (Flags = noflags) AND (Proto = UDP) AND (SrcPt = 68))
(DstPt = 445) -> ((DstIpAddr = private_p2p) AND (Flags = hasflags) AND (Proto = TCP) AND (SrcIpAddr = private_p2p) AND (SrcPt = unknown_port))
DstPt >= 0
(SrcPt = 22) -> ((DstIpAddr = private_p2p) AND (DstPt = unknown_port) AND (Flags = hasflags) AND (Proto = TCP))
Flags <= 1
((DstIpAddr = dns) AND (Proto = UDP)) -> ((DstPt = 53) AND (SrcPt = unknown_port))
((DstIpAddr = dns) AND (Flags = hasflags)) -> ((DstPt = 53) AND (SrcPt = unknown_port))
((DstIpAddr = public_p2p) AND (Flags = hasflags)) -> (SrcPt = unknown_port)
((Flags = noflags) AND (SrcPt = unknown_port)) -> (Proto = UDP)
(SrcPt = 68) -> ((DstPt = 67) AND (Flags = noflags) AND (Proto = UDP))
(DstPt = 8082) -> ((DstIpAddr = public_p2p) AND (Flags = hasflags) AND (Proto = TCP) AND (SrcIpAddr = private_p2p) AND (SrcPt = unknown_port))
((DstIpAddr = private_p2p) AND (SrcPt = 123)) -> (SrcIpAddr = public_p2p)
((DstIpAddr = private_p2p) AND (Flags = noflags) AND (SrcPt = unknown_port)) -> ((DstPt = unknown_port) AND (SrcIpAddr = public_p2p))
((DstIpAddr = private_p2p) AND (Proto = UDP) AND (SrcPt = unknown_port)) -> ((DstPt = unknown_port) AND (SrcIpAddr = public_p2p))
(SrcIpAddr = dns) -> ((DstIpAddr = private_p2p) AND (DstPt = unknown_port) AND (SrcPt = 53))
(DstPt = 587) -> ((DstIpAddr = private_p2p) AND (Flags = hasflags) AND (Proto = TCP) AND (SrcIpAddr = private_p2p) AND (SrcPt = unknown_port))
(DstPt = 443) -> ((DstIpAddr = public_p2p) AND (Flags = hasflags) AND (Proto = TCP) AND (SrcIpAddr = private_p2p) AND (SrcPt = unknown_port))
((DstPt = unknown_port) AND (Flags = noflags) AND (SrcIpAddr = public_p2p)) -> (SrcPt = unknown_port)
(Proto = UDP) -> ((42 * Packets) <= Bytes)
(Proto = UDP) -> ((65535 * Packets) >= Bytes)
(Proto = ICMP) -> ((65535 * Packets) >= Bytes)
(Proto = UDP) -> ((1500 * Packets) >= Bytes)
(65535 * Packets) >= Bytes
(42 * Packets) <= Bytes
(Proto = UDP) -> ((8 * Packets) <= Bytes)
(Proto = ICMP) -> ((64 * Packets) <= Bytes)
(Proto = TCP) -> ((42 * Packets) <= Bytes)
