(Packets * 65535) >= Bytes
DstSubnet != unspecified
Duration >= p25
Packets >= p25
SrcSubnet != unspecified
(Bytes >= p25) OR (DstSubnet != servers)
(DstPortClass != https) OR (DstSubnet != servers)
(DstPortClass != dns) OR (DstSubnet != servers)
(DstSubnet != servers) OR (DstSubnet != management)
(DstSubnet != servers) OR (DstSubnet != office)
(DstSubnet != servers) OR (DstSubnet != developer)
(DstSubnet != servers) OR (DstSubnet != public)
(DstSubnet != servers) OR (DstSubnet != dns)
(DstSubnet != servers) OR (SrcPortClass != https)
(DstSubnet != servers) OR (SrcPortClass != http)
(DstSubnet != servers) OR (SrcSubnet != public)
(Bytes < p50) OR (DstSubnet != servers) OR (SrcSubnet != office)
(Bytes < p90) OR (DstSubnet != servers) OR (SrcSubnet != office)
(Bytes < p75) OR (DstSubnet != servers) OR (SrcSubnet != office)
(Bytes <= p50) OR (DstSubnet != servers) OR (SrcSubnet != office)
(Bytes <= p90) OR (DstSubnet != servers) OR (SrcSubnet != office)
(Bytes <= p75) OR (DstSubnet != servers) OR (SrcSubnet != office)
(Bytes > p25) OR (DstSubnet != servers) OR (SrcSubnet != office)
(DstPortClass != well_known) OR (DstSubnet != servers) OR (SrcSubnet != office)
(DstPortClass != registered) OR (DstSubnet != servers) OR (SrcSubnet != office)
(DstPortClass != dynamic) OR (DstSubnet != servers) OR (SrcSubnet != office)
(DstPortClass = http) OR (DstSubnet != servers) OR (SrcSubnet != office)
(DstSubnet != servers) OR (Duration < p75) OR (SrcSubnet != office)
(DstSubnet != servers) OR (Duration < p90) OR (SrcSubnet != office)
(DstSubnet != servers) OR (Duration <= p25) OR (SrcSubnet != office)
(DstSubnet != servers) OR (Duration <= p75) OR (SrcSubnet != office)
(DstSubnet != servers) OR (Duration <= p90) OR (SrcSubnet != office)
(DstSubnet != servers) OR (Packets < p75) OR (SrcSubnet != office)
(DstSubnet != servers) OR (Packets < p90) OR (SrcSubnet != office)
(DstSubnet != servers) OR (Packets <= p75) OR (SrcSubnet != office)
(DstSubnet != servers) OR (Packets <= p90) OR (SrcSubnet != office)
(DstSubnet != servers) OR (Packets > p25) OR (SrcSubnet != office)
(DstSubnet != servers) OR (SrcPortClass != dns) OR (SrcSubnet != office)
(DstSubnet != servers) OR (SrcPortClass != well_known) OR (SrcSubnet != office)
(DstSubnet != servers) OR (SrcPortClass != registered) OR (SrcSubnet != office)
(DstSubnet != servers) OR (SrcPortClass = dynamic) OR (SrcSubnet != office)
(DstSubnet != servers) OR (SrcSubnet != servers) OR (SrcSubnet != office)
(DstSubnet != servers) OR (SrcSubnet != management) OR (SrcSubnet != office)
(DstSubnet != servers) OR (SrcSubnet != office) OR (SrcSubnet != developer)
(DstSubnet != servers) OR (SrcSubnet != office) OR (SrcSubnet != dns)
(Bytes < p50) OR (DstPortClass != dynamic) OR (DstSubnet != servers)
(Bytes < p90) OR (DstPortClass != dynamic) OR (DstSubnet != servers)
(Bytes < p75) OR (DstPortClass != dynamic) OR (DstSubnet != servers)
(Bytes <= p50) OR (DstPortClass != dynamic) OR (DstSubnet != servers)
(Bytes <= p90) OR (DstPortClass != dynamic) OR (DstSubnet != servers)
(Bytes <= p75) OR (DstPortClass != dynamic) OR (DstSubnet != servers)
(Bytes > p25) OR (DstPortClass != dynamic) OR (DstSubnet != servers)
(DstPortClass != well_known) OR (DstPortClass != dynamic) OR (DstSubnet != servers)
(DstPortClass != registered) OR (DstPortClass != dynamic) OR (DstSubnet != servers)
(DstPortClass != dynamic) OR (DstPortClass != http) OR (DstSubnet != servers)
(DstPortClass != dynamic) OR (DstSubnet != servers) OR (Duration < p75)
(DstPortClass != dynamic) OR (DstSubnet != servers) OR (Duration < p90)
(DstPortClass != dynamic) OR (DstSubnet != servers) OR (Duration <= p25)
(DstPortClass != dynamic) OR (DstSubnet != servers) OR (Duration <= p75)
(DstPortClass != dynamic) OR (DstSubnet != servers) OR (Duration <= p90)
(DstPortClass != dynamic) OR (DstSubnet != servers) OR (Packets < p75)
(DstPortClass != dynamic) OR (DstSubnet != servers) OR (Packets < p90)
(DstPortClass != dynamic) OR (DstSubnet != servers) OR (Packets <= p25)
(DstPortClass != dynamic) OR (DstSubnet != servers) OR (Packets <= p75)
(DstPortClass != dynamic) OR (DstSubnet != servers) OR (Packets <= p90)
(DstPortClass != dynamic) OR (DstSubnet != servers) OR (SrcPortClass != well_known)
(DstPortClass != dynamic) OR (DstSubnet != servers) OR (SrcPortClass != registered)
(DstPortClass != dynamic) OR (DstSubnet != servers) OR (SrcPortClass != dynamic)
(DstPortClass != dynamic) OR (DstSubnet != servers) OR (SrcPortClass = dns)
(DstPortClass != dynamic) OR (DstSubnet != servers) OR (SrcSubnet != servers)
(DstPortClass != dynamic) OR (DstSubnet != servers) OR (SrcSubnet != management)
(DstPortClass != dynamic) OR (DstSubnet != servers) OR (SrcSubnet != developer)
(DstPortClass != dynamic) OR (DstSubnet != servers) OR (SrcSubnet = dns)
(Bytes < p90) OR (DstSubnet != servers) OR (Duration < p90)
(Bytes < p75) OR (DstSubnet != servers) OR (Duration < p90)
(Bytes <= p90) OR (DstSubnet != servers) OR (Duration < p90)
(Bytes <= p75) OR (DstSubnet != servers) OR (Duration < p90)
(Bytes > p50) OR (DstSubnet != servers) OR (Duration < p90)
(Bytes > p25) OR (DstSubnet != servers) OR (Duration < p90)
(Bytes >= p50) OR (DstSubnet != servers) OR (Duration < p90)
(DstPortClass != registered) OR (DstSubnet != servers) OR (Duration < p90)
(DstPortClass != http) OR (DstSubnet != servers) OR (Duration < p90)
(DstPortClass = well_known) OR (DstSubnet != servers) OR (Duration < p90)
(DstSubnet != servers) OR (Duration < p90) OR (Duration > p25)
(DstSubnet != servers) OR (Duration < p90) OR (Duration > p75)
(DstSubnet != servers) OR (Duration < p90) OR (Duration > p90)
(DstSubnet != servers) OR (Duration < p90) OR (Duration >= p75)
(DstSubnet != servers) OR (Duration < p90) OR (Packets < p90)
(DstSubnet != servers) OR (Duration < p90) OR (Packets <= p75)
(DstSubnet != servers) OR (Duration < p90) OR (Packets <= p90)
(DstSubnet != servers) OR (Duration < p90) OR (Packets > p25)
(DstSubnet != servers) OR (Duration < p90) OR (Packets >= p75)
(DstSubnet != servers) OR (Duration < p90) OR (SrcPortClass != dns)
(DstSubnet != servers) OR (Duration < p90) OR (SrcPortClass != well_known)
(DstSubnet != servers) OR (Duration < p90) OR (SrcPortClass != registered)
(DstSubnet != servers) OR (Duration < p90) OR (SrcPortClass = dynamic)
(DstSubnet != servers) OR (Duration < p90) OR (SrcSubnet != servers)
(DstSubnet != servers) OR (Duration < p90) OR (SrcSubnet != management)
(DstSubnet != servers) OR (Duration < p90) OR (SrcSubnet != dns)
(DstSubnet != servers) OR (Duration < p90) OR (SrcSubnet = developer)
(Bytes < p90) OR (DstSubnet != servers) OR (Duration <= p90)
(Bytes < p75) OR (DstSubnet != servers) OR (Duration <= p90)
(Bytes <= p90) OR (DstSubnet != servers) OR (Duration <= p90)
(Bytes <= p75) OR (DstSubnet != servers) OR (Duration <= p90)
(Bytes > p50) OR (DstSubnet != servers) OR (Duration <= p90)
(Bytes > p25) OR (DstSubnet != servers) OR (Duration <= p90)
(Bytes >= p50) OR (DstSubnet != servers) OR (Duration <= p90)
(DstPortClass != registered) OR (DstSubnet != servers) OR (Duration <= p90)
(DstPortClass != http) OR (DstSubnet != servers) OR (Duration <= p90)
(DstPortClass = well_known) OR (DstSubnet != servers) OR (Duration <= p90)
(DstSubnet != servers) OR (Duration <= p90) OR (Duration > p25)
(DstSubnet != servers) OR (Duration <= p90) OR (Duration > p75)
(DstSubnet != servers) OR (Duration <= p90) OR (Duration >= p75)
(DstSubnet != servers) OR (Duration <= p90) OR (Duration >= p90)
(DstSubnet != servers) OR (Duration <= p90) OR (Packets < p90)
(DstSubnet != servers) OR (Duration <= p90) OR (Packets <= p75)
(DstSubnet != servers) OR (Duration <= p90) OR (Packets <= p90)
(DstSubnet != servers) OR (Duration <= p90) OR (Packets > p25)
(DstSubnet != servers) OR (Duration <= p90) OR (Packets >= p75)
(DstSubnet != servers) OR (Duration <= p90) OR (SrcPortClass != dns)
(DstSubnet != servers) OR (Duration <= p90) OR (SrcPortClass != well_known)
(DstSubnet != servers) OR (Duration <= p90) OR (SrcPortClass != registered)
(DstSubnet != servers) OR (Duration <= p90) OR (SrcPortClass = dynamic)
(DstSubnet != servers) OR (Duration <= p90) OR (SrcSubnet != servers)
(DstSubnet != servers) OR (Duration <= p90) OR (SrcSubnet != management)
(DstSubnet != servers) OR (Duration <= p90) OR (SrcSubnet != dns)
(DstSubnet != servers) OR (Duration <= p90) OR (SrcSubnet = developer)
(Bytes < p50) OR (DstPortClass != registered) OR (DstSubnet != servers)
(Bytes < p90) OR (DstPortClass != registered) OR (DstSubnet != servers)
(Bytes < p75) OR (DstPortClass != registered) OR (DstSubnet != servers)
(Bytes <= p50) OR (DstPortClass != registered) OR (DstSubnet != servers)
(Bytes <= p90) OR (DstPortClass != registered) OR (DstSubnet != servers)
(Bytes <= p75) OR (DstPortClass != registered) OR (DstSubnet != servers)
(Bytes > p25) OR (DstPortClass != registered) OR (DstSubnet != servers)
(DstPortClass != well_known) OR (DstPortClass != registered) OR (DstSubnet != servers)
(DstPortClass != registered) OR (DstPortClass != http) OR (DstSubnet != servers)
(DstPortClass != registered) OR (DstSubnet != servers) OR (Duration < p75)
(DstPortClass != registered) OR (DstSubnet != servers) OR (Duration <= p25)
(DstPortClass != registered) OR (DstSubnet != servers) OR (Duration <= p75)
(DstPortClass != registered) OR (DstSubnet != servers) OR (Packets < p75)
(DstPortClass != registered) OR (DstSubnet != servers) OR (Packets < p90)
(DstPortClass != registered) OR (DstSubnet != servers) OR (Packets <= p25)
(DstPortClass != registered) OR (DstSubnet != servers) OR (Packets <= p75)
(DstPortClass != registered) OR (DstSubnet != servers) OR (Packets <= p90)
(DstPortClass != registered) OR (DstSubnet != servers) OR (SrcPortClass != well_known)
(DstPortClass != registered) OR (DstSubnet != servers) OR (SrcPortClass != registered)
(DstPortClass != registered) OR (DstSubnet != servers) OR (SrcPortClass != dynamic)
(DstPortClass != registered) OR (DstSubnet != servers) OR (SrcPortClass = dns)
(DstPortClass != registered) OR (DstSubnet != servers) OR (SrcSubnet != servers)
(DstPortClass != registered) OR (DstSubnet != servers) OR (SrcSubnet != management)
(DstPortClass != registered) OR (DstSubnet != servers) OR (SrcSubnet != developer)
(DstPortClass != registered) OR (DstSubnet != servers) OR (SrcSubnet = dns)
(Bytes < p90) OR (Bytes > p50) OR (DstSubnet != servers)
(Bytes < p90) OR (Bytes > p90) OR (DstSubnet != servers)
(Bytes < p90) OR (Bytes > p75) OR (DstSubnet != servers)
(Bytes < p90) OR (Bytes > p25) OR (DstSubnet != servers)
(Bytes < p90) OR (Bytes >= p50) OR (DstSubnet != servers)
(Bytes < p90) OR (Bytes >= p75) OR (DstSubnet != servers)
(Bytes < p90) OR (DstPortClass != http) OR (DstSubnet != servers)
(Bytes < p90) OR (DstPortClass = well_known) OR (DstSubnet != servers)
(Bytes < p90) OR (DstSubnet != servers) OR (Duration > p25)
(Bytes < p90) OR (DstSubnet != servers) OR (Packets > p25)
(Bytes < p90) OR (DstSubnet != servers) OR (Packets > p75)
(Bytes < p90) OR (DstSubnet != servers) OR (Packets >= p75)
(Bytes < p90) OR (DstSubnet != servers) OR (Packets >= p90)
(Bytes < p90) OR (DstSubnet != servers) OR (SrcPortClass != dns)
(Bytes < p90) OR (DstSubnet != servers) OR (SrcPortClass != well_known)
(Bytes < p90) OR (DstSubnet != servers) OR (SrcSubnet != servers)
(Bytes < p90) OR (DstSubnet != servers) OR (SrcSubnet != management)
(Bytes < p90) OR (DstSubnet != servers) OR (SrcSubnet != dns)
(Bytes < p90) OR (DstSubnet != servers) OR (SrcSubnet = developer)
(Bytes < p90) OR (DstSubnet != servers) OR (Duration > p75) OR (Packets > p90)
(Bytes < p90) OR (DstSubnet != servers) OR (Duration > p75) OR (SrcPortClass != dynamic)
(Bytes < p90) OR (DstSubnet != servers) OR (Duration > p75) OR (SrcPortClass = registered)
(Bytes < p90) OR (DstSubnet != servers) OR (Duration >= p75) OR (Packets > p90)
(Bytes < p90) OR (DstSubnet != servers) OR (Duration >= p75) OR (SrcPortClass != dynamic)
(Bytes < p90) OR (DstSubnet != servers) OR (Duration >= p75) OR (SrcPortClass = registered)
(Bytes < p90) OR (DstSubnet != servers) OR (Packets > p90) OR (SrcPortClass != registered)
(Bytes < p90) OR (DstSubnet != servers) OR (Packets > p90) OR (SrcPortClass = dynamic)
(Bytes < p90) OR (DstSubnet != servers) OR (SrcPortClass != registered) OR (SrcPortClass != dynamic)
(Bytes < p90) OR (DstSubnet != servers) OR (SrcPortClass = registered) OR (SrcPortClass = dynamic)
(Bytes <= p90) OR (Bytes > p50) OR (DstSubnet != servers)
(Bytes <= p90) OR (Bytes > p75) OR (DstSubnet != servers)
(Bytes <= p90) OR (Bytes > p25) OR (DstSubnet != servers)
(Bytes <= p90) OR (Bytes >= p50) OR (DstSubnet != servers)
(Bytes <= p90) OR (Bytes >= p90) OR (DstSubnet != servers)
(Bytes <= p90) OR (Bytes >= p75) OR (DstSubnet != servers)
(Bytes <= p90) OR (DstPortClass != http) OR (DstSubnet != servers)
(Bytes <= p90) OR (DstPortClass = well_known) OR (DstSubnet != servers)
(Bytes <= p90) OR (DstSubnet != servers) OR (Duration > p25)
(Bytes <= p90) OR (DstSubnet != servers) OR (Packets > p25)
(Bytes <= p90) OR (DstSubnet != servers) OR (Packets > p75)
(Bytes <= p90) OR (DstSubnet != servers) OR (Packets >= p75)
(Bytes <= p90) OR (DstSubnet != servers) OR (Packets >= p90)
(Bytes <= p90) OR (DstSubnet != servers) OR (SrcPortClass != dns)
(Bytes <= p90) OR (DstSubnet != servers) OR (SrcPortClass != well_known)
(Bytes <= p90) OR (DstSubnet != servers) OR (SrcSubnet != servers)
(Bytes <= p90) OR (DstSubnet != servers) OR (SrcSubnet != management)
(Bytes <= p90) OR (DstSubnet != servers) OR (SrcSubnet != dns)
(Bytes <= p90) OR (DstSubnet != servers) OR (SrcSubnet = developer)
(Bytes <= p90) OR (DstSubnet != servers) OR (Duration > p75) OR (Packets > p90)
(Bytes <= p90) OR (DstSubnet != servers) OR (Duration > p75) OR (SrcPortClass != dynamic)
(Bytes <= p90) OR (DstSubnet != servers) OR (Duration > p75) OR (SrcPortClass = registered)
(Bytes <= p90) OR (DstSubnet != servers) OR (Duration >= p75) OR (Packets > p90)
(Bytes <= p90) OR (DstSubnet != servers) OR (Duration >= p75) OR (SrcPortClass != dynamic)
(Bytes <= p90) OR (DstSubnet != servers) OR (Duration >= p75) OR (SrcPortClass = registered)
(Bytes <= p90) OR (DstSubnet != servers) OR (Packets > p90) OR (SrcPortClass != registered)
(Bytes <= p90) OR (DstSubnet != servers) OR (Packets > p90) OR (SrcPortClass = dynamic)
(Bytes <= p90) OR (DstSubnet != servers) OR (SrcPortClass != registered) OR (SrcPortClass != dynamic)
(Bytes <= p90) OR (DstSubnet != servers) OR (SrcPortClass = registered) OR (SrcPortClass = dynamic)
(Bytes < p50) OR (DstSubnet != servers) OR (SrcPortClass != dns)
(Bytes < p75) OR (DstSubnet != servers) OR (SrcPortClass != dns)
(Bytes <= p50) OR (DstSubnet != servers) OR (SrcPortClass != dns)
(Bytes <= p75) OR (DstSubnet != servers) OR (SrcPortClass != dns)
(Bytes > p25) OR (DstSubnet != servers) OR (SrcPortClass != dns)
(DstPortClass != well_known) OR (DstSubnet != servers) OR (SrcPortClass != dns)
(DstPortClass != http) OR (DstSubnet != servers) OR (SrcPortClass != dns)
(DstSubnet != servers) OR (Duration < p75) OR (SrcPortClass != dns)
(DstSubnet != servers) OR (Duration <= p25) OR (SrcPortClass != dns)
(DstSubnet != servers) OR (Duration <= p75) OR (SrcPortClass != dns)
(DstSubnet != servers) OR (Packets < p75) OR (SrcPortClass != dns)
(DstSubnet != servers) OR (Packets < p90) OR (SrcPortClass != dns)
(DstSubnet != servers) OR (Packets <= p25) OR (SrcPortClass != dns)
(DstSubnet != servers) OR (Packets <= p75) OR (SrcPortClass != dns)
(DstSubnet != servers) OR (Packets <= p90) OR (SrcPortClass != dns)
(DstSubnet != servers) OR (SrcPortClass != dns) OR (SrcPortClass != well_known)
(DstSubnet != servers) OR (SrcPortClass != dns) OR (SrcPortClass != registered)
(DstSubnet != servers) OR (SrcPortClass != dns) OR (SrcPortClass != dynamic)
(DstSubnet != servers) OR (SrcPortClass != dns) OR (SrcSubnet != servers)
(DstSubnet != servers) OR (SrcPortClass != dns) OR (SrcSubnet != management)
(DstSubnet != servers) OR (SrcPortClass != dns) OR (SrcSubnet != developer)
(DstSubnet != servers) OR (SrcPortClass != dns) OR (SrcSubnet = dns)
(DstPortClass = registered) OR (DstPortClass = dynamic) OR (DstSubnet != servers) OR (SrcPortClass != dns)
(Bytes < p50) OR (DstSubnet != servers) OR (SrcSubnet != dns)
(Bytes < p75) OR (DstSubnet != servers) OR (SrcSubnet != dns)
(Bytes <= p50) OR (DstSubnet != servers) OR (SrcSubnet != dns)
(Bytes <= p75) OR (DstSubnet != servers) OR (SrcSubnet != dns)
(Bytes > p25) OR (DstSubnet != servers) OR (SrcSubnet != dns)
(DstPortClass != well_known) OR (DstSubnet != servers) OR (SrcSubnet != dns)
(DstPortClass != http) OR (DstSubnet != servers) OR (SrcSubnet != dns)
(DstSubnet != servers) OR (Duration < p75) OR (SrcSubnet != dns)
(DstSubnet != servers) OR (Duration <= p25) OR (SrcSubnet != dns)
(DstSubnet != servers) OR (Duration <= p75) OR (SrcSubnet != dns)
(DstSubnet != servers) OR (Packets < p75) OR (SrcSubnet != dns)
(DstSubnet != servers) OR (Packets < p90) OR (SrcSubnet != dns)
(DstSubnet != servers) OR (Packets <= p25) OR (SrcSubnet != dns)
(DstSubnet != servers) OR (Packets <= p75) OR (SrcSubnet != dns)
(DstSubnet != servers) OR (Packets <= p90) OR (SrcSubnet != dns)
(DstSubnet != servers) OR (SrcPortClass != well_known) OR (SrcSubnet != dns)
(DstSubnet != servers) OR (SrcPortClass != registered) OR (SrcSubnet != dns)
(DstSubnet != servers) OR (SrcPortClass != dynamic) OR (SrcSubnet != dns)
(DstSubnet != servers) OR (SrcPortClass = dns) OR (SrcSubnet != dns)
(DstSubnet != servers) OR (SrcSubnet != servers) OR (SrcSubnet != dns)
(DstSubnet != servers) OR (SrcSubnet != management) OR (SrcSubnet != dns)
(DstSubnet != servers) OR (SrcSubnet != developer) OR (SrcSubnet != dns)
(DstPortClass = registered) OR (DstPortClass = dynamic) OR (DstSubnet != servers) OR (SrcSubnet != dns)
(DstPortClass != well_known) OR (DstPortClass != http) OR (DstSubnet != servers)
(DstPortClass != http) OR (DstSubnet != servers) OR (Duration < p75)
(DstPortClass != http) OR (DstSubnet != servers) OR (Duration <= p75)
(DstPortClass != http) OR (DstSubnet != servers) OR (Packets < p90)
(DstPortClass != http) OR (DstSubnet != servers) OR (Packets <= p90)
(DstPortClass != http) OR (DstSubnet != servers) OR (SrcPortClass != well_known)
(DstPortClass != http) OR (DstSubnet != servers) OR (SrcSubnet != servers)
(Bytes < p75) OR (DstPortClass != http) OR (DstSubnet != servers) OR (Duration > p25)
(Bytes < p75) OR (DstPortClass != http) OR (DstSubnet != servers) OR (Packets > p75)
(Bytes < p75) OR (DstPortClass != http) OR (DstSubnet != servers) OR (Packets >= p75)
(Bytes < p75) OR (DstPortClass != http) OR (DstSubnet != servers) OR (SrcPortClass != registered)
(Bytes < p75) OR (DstPortClass != http) OR (DstSubnet != servers) OR (SrcPortClass = dynamic)
(Bytes < p75) OR (DstPortClass != http) OR (DstSubnet != servers) OR (SrcSubnet != developer)
(Bytes < p75) OR (DstPortClass != http) OR (DstSubnet != servers) OR (SrcSubnet = management)
(Bytes <= p50) OR (Bytes > p75) OR (DstPortClass != http) OR (DstSubnet != servers)
(Bytes <= p50) OR (Bytes > p25) OR (DstPortClass != http) OR (DstSubnet != servers)
(Bytes <= p50) OR (Bytes >= p50) OR (DstPortClass != http) OR (DstSubnet != servers)
(Bytes <= p50) OR (Bytes >= p75) OR (DstPortClass != http) OR (DstSubnet != servers)
(Bytes <= p50) OR (DstPortClass != http) OR (DstSubnet != servers) OR (Duration > p25)
(Bytes <= p50) OR (DstPortClass != http) OR (DstSubnet != servers) OR (Packets > p25)
(Bytes <= p50) OR (DstPortClass != http) OR (DstSubnet != servers) OR (Packets > p75)
(Bytes <= p50) OR (DstPortClass != http) OR (DstSubnet != servers) OR (Packets >= p75)
(Bytes <= p50) OR (DstPortClass != http) OR (DstSubnet != servers) OR (SrcPortClass != registered)
(Bytes <= p50) OR (DstPortClass != http) OR (DstSubnet != servers) OR (SrcPortClass = dynamic)
(Bytes <= p50) OR (DstPortClass != http) OR (DstSubnet != servers) OR (SrcSubnet != developer)
(Bytes <= p50) OR (DstPortClass != http) OR (DstSubnet != servers) OR (SrcSubnet = management)
(Bytes <= p75) OR (DstPortClass != http) OR (DstSubnet != servers) OR (Duration > p25)
(Bytes <= p75) OR (DstPortClass != http) OR (DstSubnet != servers) OR (Packets > p75)
(Bytes <= p75) OR (DstPortClass != http) OR (DstSubnet != servers) OR (Packets >= p75)
(Bytes <= p75) OR (DstPortClass != http) OR (DstSubnet != servers) OR (SrcPortClass != registered)
(Bytes <= p75) OR (DstPortClass != http) OR (DstSubnet != servers) OR (SrcPortClass = dynamic)
(Bytes <= p75) OR (DstPortClass != http) OR (DstSubnet != servers) OR (SrcSubnet != developer)
(Bytes <= p75) OR (DstPortClass != http) OR (DstSubnet != servers) OR (SrcSubnet = management)
(Bytes < p50) OR (Bytes > p25) OR (DstPortClass != http) OR (DstSubnet != servers)
(Bytes > p25) OR (DstPortClass != http) OR (DstSubnet != servers) OR (Duration <= p25)
(Bytes > p25) OR (DstPortClass != http) OR (DstSubnet != servers) OR (Packets <= p25)
(Bytes > p25) OR (DstPortClass != http) OR (DstSubnet != servers) OR (SrcPortClass != dynamic)
(Bytes > p25) OR (DstPortClass != http) OR (DstSubnet != servers) OR (SrcPortClass = registered)
(Bytes > p25) OR (DstPortClass != http) OR (DstSubnet != servers) OR (SrcSubnet != management)
(Bytes > p25) OR (DstPortClass != http) OR (DstSubnet != servers) OR (SrcSubnet = developer)
(Bytes > p75) OR (DstPortClass != http) OR (DstSubnet != servers) OR (Packets < p75)
(Bytes >= p75) OR (DstPortClass != http) OR (DstSubnet != servers) OR (Packets < p75)
(DstPortClass != http) OR (DstSubnet != servers) OR (Packets < p75) OR (Packets > p75)
(DstPortClass != http) OR (DstSubnet != servers) OR (Packets < p75) OR (SrcPortClass != registered)
(DstPortClass != http) OR (DstSubnet != servers) OR (Packets < p75) OR (SrcPortClass = dynamic)
(DstPortClass != http) OR (DstSubnet != servers) OR (Packets < p75) OR (SrcSubnet != developer)
(DstPortClass != http) OR (DstSubnet != servers) OR (Packets < p75) OR (SrcSubnet = management)
(DstPortClass != http) OR (DstSubnet != servers) OR (Packets <= p75) OR (SrcPortClass != registered)
(DstPortClass != http) OR (DstSubnet != servers) OR (Packets <= p75) OR (SrcPortClass = dynamic)
(DstPortClass != http) OR (DstSubnet != servers) OR (Packets <= p75) OR (SrcSubnet != developer)
(DstPortClass != http) OR (DstSubnet != servers) OR (Packets <= p75) OR (SrcSubnet = management)
(Bytes < p50) OR (DstPortClass != http) OR (DstSubnet != servers) OR (Packets > p25)
(Bytes <= p25) OR (DstPortClass != http) OR (DstSubnet != servers) OR (Packets > p25)
(DstPortClass != http) OR (DstSubnet != servers) OR (Duration <= p25) OR (Packets > p25)
(DstPortClass != http) OR (DstSubnet != servers) OR (Packets > p25) OR (SrcPortClass != dynamic)
(DstPortClass != http) OR (DstSubnet != servers) OR (Packets > p25) OR (SrcPortClass = registered)
(DstPortClass != http) OR (DstSubnet != servers) OR (Packets > p25) OR (SrcSubnet != management)
(DstPortClass != http) OR (DstSubnet != servers) OR (Packets > p25) OR (SrcSubnet = developer)
(DstPortClass != http) OR (DstSubnet != servers) OR (SrcPortClass != registered) OR (SrcSubnet != management)
(DstPortClass != http) OR (DstSubnet != servers) OR (SrcPortClass = dynamic) OR (SrcSubnet != management)
(DstPortClass != http) OR (DstSubnet != servers) OR (SrcSubnet != management) OR (SrcSubnet != developer)
(Bytes < p50) OR (Bytes > p50) OR (DstPortClass != http) OR (DstSubnet != servers) OR (SrcSubnet != management)
(Bytes > p50) OR (DstPortClass != http) OR (DstSubnet != servers) OR (Duration <= p25) OR (SrcSubnet != management)
(Bytes < p50) OR (Bytes > p75) OR (DstPortClass != http) OR (DstSubnet != servers) OR (SrcSubnet != management)
(Bytes > p75) OR (DstPortClass != http) OR (DstSubnet != servers) OR (Duration <= p25) OR (SrcSubnet != management)
(Bytes < p50) OR (Bytes >= p75) OR (DstPortClass != http) OR (DstSubnet != servers) OR (SrcSubnet != management)
(Bytes >= p75) OR (DstPortClass != http) OR (DstSubnet != servers) OR (Duration <= p25) OR (SrcSubnet != management)
(Bytes < p50) OR (DstPortClass != http) OR (DstSubnet != servers) OR (Packets > p75) OR (SrcSubnet != management)
(DstPortClass != http) OR (DstSubnet != servers) OR (Duration <= p25) OR (Packets > p75) OR (SrcSubnet != management)
(Bytes < p50) OR (DstPortClass != http) OR (DstSubnet != servers) OR (Packets >= p75) OR (SrcSubnet != management)
(DstPortClass != http) OR (DstSubnet != servers) OR (Duration <= p25) OR (Packets >= p75) OR (SrcSubnet != management)
(Bytes >= p50) OR (DstPortClass != http) OR (DstSubnet != servers) OR (Duration <= p25)
(Bytes <= p25) OR (Bytes >= p50) OR (DstPortClass != http) OR (DstSubnet != servers) OR (SrcPortClass != registered)
(Bytes <= p25) OR (Bytes >= p50) OR (DstPortClass != http) OR (DstSubnet != servers) OR (SrcPortClass = dynamic)
(Bytes <= p25) OR (Bytes >= p50) OR (DstPortClass != http) OR (DstSubnet != servers) OR (SrcSubnet != developer)
(Bytes <= p25) OR (Bytes >= p50) OR (DstPortClass != http) OR (DstSubnet != servers) OR (SrcSubnet = management) OR (SrcSubnet = office)
(Bytes >= p50) OR (DstPortClass != http) OR (DstSubnet != servers) OR (Packets <= p25) OR (SrcPortClass != registered)
(Bytes >= p50) OR (DstPortClass != http) OR (DstSubnet != servers) OR (Packets <= p25) OR (SrcPortClass = dynamic)
(Bytes >= p50) OR (DstPortClass != http) OR (DstSubnet != servers) OR (Packets <= p25) OR (SrcSubnet != developer)
(Bytes >= p50) OR (DstPortClass != http) OR (DstSubnet != servers) OR (Packets <= p25) OR (SrcSubnet = management) OR (SrcSubnet = office)
(Bytes >= p50) OR (DstPortClass != http) OR (DstSubnet != servers) OR (SrcPortClass != dynamic) OR (SrcSubnet != developer)
(Bytes >= p50) OR (DstPortClass != http) OR (DstSubnet != servers) OR (SrcPortClass != dynamic) OR (SrcSubnet = management) OR (SrcSubnet = office)
(Bytes >= p50) OR (DstPortClass != http) OR (DstSubnet != servers) OR (SrcPortClass = registered) OR (SrcSubnet != developer)
(Bytes >= p50) OR (DstPortClass != http) OR (DstSubnet != servers) OR (SrcPortClass = registered) OR (SrcSubnet = management) OR (SrcSubnet = office)
(Bytes < p50) OR (DstPortClass != http) OR (DstSubnet != servers) OR (Duration > p25)
(Bytes <= p25) OR (DstPortClass != http) OR (DstSubnet != servers) OR (Duration > p25) OR (SrcPortClass != registered)
(Bytes <= p25) OR (DstPortClass != http) OR (DstSubnet != servers) OR (Duration > p25) OR (SrcPortClass = dynamic)
(Bytes <= p25) OR (DstPortClass != http) OR (DstSubnet != servers) OR (Duration > p25) OR (SrcSubnet != developer)
(Bytes <= p25) OR (DstPortClass != http) OR (DstSubnet != servers) OR (Duration > p25) OR (SrcSubnet = management) OR (SrcSubnet = office)
(DstPortClass != http) OR (DstSubnet != servers) OR (Duration > p25) OR (Packets <= p25) OR (SrcPortClass != registered)
(DstPortClass != http) OR (DstSubnet != servers) OR (Duration > p25) OR (Packets <= p25) OR (SrcPortClass = dynamic)
(DstPortClass != http) OR (DstSubnet != servers) OR (Duration > p25) OR (Packets <= p25) OR (SrcSubnet != developer)
(DstPortClass != http) OR (DstSubnet != servers) OR (Duration > p25) OR (Packets <= p25) OR (SrcSubnet = management) OR (SrcSubnet = office)
(DstPortClass != http) OR (DstSubnet != servers) OR (Duration > p25) OR (SrcPortClass != dynamic) OR (SrcSubnet != developer)
(DstPortClass != http) OR (DstSubnet != servers) OR (Duration > p25) OR (SrcPortClass != dynamic) OR (SrcSubnet = management) OR (SrcSubnet = office)
(DstPortClass != http) OR (DstSubnet != servers) OR (Duration > p25) OR (SrcPortClass = registered) OR (SrcSubnet != developer)
(DstPortClass != http) OR (DstSubnet != servers) OR (Duration > p25) OR (SrcPortClass = registered) OR (SrcSubnet = management) OR (SrcSubnet = office)
(DstPortClass != http) OR (DstSubnet != servers) OR (SrcPortClass != registered) OR (SrcSubnet = developer)
(DstPortClass != http) OR (DstSubnet != servers) OR (SrcPortClass = dynamic) OR (SrcSubnet = developer)
(Bytes < p50) OR (DstPortClass != http) OR (DstSubnet != servers) OR (SrcSubnet = management) OR (SrcSubnet = developer)
(DstPortClass != http) OR (DstSubnet != servers) OR (Duration <= p25) OR (SrcSubnet = management) OR (SrcSubnet = developer)
(DstPortClass != http) OR (DstSubnet != servers) OR (SrcSubnet = management) OR (SrcSubnet = office) OR (SrcSubnet = developer)
(Bytes < p50) OR (Bytes > p50) OR (DstPortClass != http) OR (DstSubnet != servers) OR (SrcSubnet = developer)
(Bytes > p50) OR (DstPortClass != http) OR (DstSubnet != servers) OR (Duration <= p25) OR (SrcSubnet = developer)
(Bytes < p50) OR (Bytes > p75) OR (DstPortClass != http) OR (DstSubnet != servers) OR (SrcSubnet = developer)
(Bytes > p75) OR (DstPortClass != http) OR (DstSubnet != servers) OR (Duration <= p25) OR (SrcSubnet = developer)
(Bytes < p50) OR (Bytes >= p75) OR (DstPortClass != http) OR (DstSubnet != servers) OR (SrcSubnet = developer)
(Bytes >= p75) OR (DstPortClass != http) OR (DstSubnet != servers) OR (Duration <= p25) OR (SrcSubnet = developer)
(Bytes < p50) OR (DstPortClass != http) OR (DstSubnet != servers) OR (Packets > p75) OR (SrcSubnet = developer)
(DstPortClass != http) OR (DstSubnet != servers) OR (Duration <= p25) OR (Packets > p75) OR (SrcSubnet = developer)
(Bytes < p50) OR (DstPortClass != http) OR (DstSubnet != servers) OR (Packets >= p75) OR (SrcSubnet = developer)
(DstPortClass != http) OR (DstSubnet != servers) OR (Duration <= p25) OR (Packets >= p75) OR (SrcSubnet = developer)
(DstPortClass != http) OR (DstSubnet != servers) OR (SrcPortClass != registered) OR (SrcPortClass != dynamic)
(DstPortClass != http) OR (DstSubnet != servers) OR (SrcPortClass = registered) OR (SrcPortClass = dynamic)
(Bytes > p50) OR (DstSubnet != servers) OR (Packets <= p90)
(Bytes > p75) OR (DstSubnet != servers) OR (Packets <= p90)
(Bytes > p25) OR (DstSubnet != servers) OR (Packets <= p90)
(Bytes >= p50) OR (DstSubnet != servers) OR (Packets <= p90)
(Bytes >= p75) OR (DstSubnet != servers) OR (Packets <= p90)
(DstPortClass = well_known) OR (DstSubnet != servers) OR (Packets <= p90)
(DstSubnet != servers) OR (Duration > p25) OR (Packets <= p90)
(DstSubnet != servers) OR (Packets <= p90) OR (Packets > p25)
(DstSubnet != servers) OR (Packets <= p90) OR (Packets > p75)
(DstSubnet != servers) OR (Packets <= p90) OR (Packets >= p75)
(DstSubnet != servers) OR (Packets <= p90) OR (Packets >= p90)
(DstSubnet != servers) OR (Packets <= p90) OR (SrcPortClass != well_known)
(DstSubnet != servers) OR (Packets <= p90) OR (SrcSubnet != servers)
(DstSubnet != servers) OR (Packets <= p90) OR (SrcSubnet != management)
(DstSubnet != servers) OR (Packets <= p90) OR (SrcSubnet = developer)
(Bytes > p90) OR (DstSubnet != servers) OR (Duration > p75) OR (Packets <= p90)
(Bytes >= p90) OR (DstSubnet != servers) OR (Duration > p75) OR (Packets <= p90)
(DstSubnet != servers) OR (Duration > p75) OR (Packets <= p90) OR (SrcPortClass != dynamic)
(DstSubnet != servers) OR (Duration > p75) OR (Packets <= p90) OR (SrcPortClass = registered)
(Bytes > p90) OR (DstSubnet != servers) OR (Duration >= p75) OR (Packets <= p90)
(Bytes >= p90) OR (DstSubnet != servers) OR (Duration >= p75) OR (Packets <= p90)
(DstSubnet != servers) OR (Duration >= p75) OR (Packets <= p90) OR (SrcPortClass != dynamic)
(DstSubnet != servers) OR (Duration >= p75) OR (Packets <= p90) OR (SrcPortClass = registered)
(DstSubnet != servers) OR (Packets <= p90) OR (SrcPortClass != registered) OR (SrcPortClass != dynamic)
(DstSubnet != servers) OR (Packets <= p90) OR (SrcPortClass = registered) OR (SrcPortClass = dynamic)
(Bytes > p25) OR (DstSubnet != servers) OR (SrcPortClass != well_known)
(DstPortClass = well_known) OR (DstSubnet != servers) OR (SrcPortClass != well_known)
(DstSubnet != servers) OR (Duration < p75) OR (SrcPortClass != well_known)
(DstSubnet != servers) OR (Duration <= p25) OR (SrcPortClass != well_known)
(DstSubnet != servers) OR (Duration <= p75) OR (SrcPortClass != well_known)
(DstSubnet != servers) OR (Packets < p75) OR (SrcPortClass != well_known)
(DstSubnet != servers) OR (Packets < p90) OR (SrcPortClass != well_known)
(DstSubnet != servers) OR (Packets <= p75) OR (SrcPortClass != well_known)
(DstSubnet != servers) OR (SrcPortClass != well_known) OR (SrcPortClass != registered)
(DstSubnet != servers) OR (SrcPortClass != well_known) OR (SrcPortClass != dynamic)
(DstSubnet != servers) OR (SrcPortClass != well_known) OR (SrcSubnet != management)
(DstSubnet != servers) OR (SrcPortClass != well_known) OR (SrcSubnet != developer)
(DstSubnet != servers) OR (SrcPortClass != well_known) OR (SrcSubnet = servers)
(Bytes > p50) OR (DstSubnet != servers) OR (Packets <= p25) OR (SrcPortClass != well_known)
(Bytes > p75) OR (DstSubnet != servers) OR (Packets <= p25) OR (SrcPortClass != well_known)
(Bytes >= p50) OR (DstSubnet != servers) OR (Packets <= p25) OR (SrcPortClass != well_known)
(Bytes >= p75) OR (DstSubnet != servers) OR (Packets <= p25) OR (SrcPortClass != well_known)
(Bytes < p50) OR (Bytes > p50) OR (DstSubnet != servers) OR (SrcPortClass != well_known)
(Bytes <= p50) OR (Bytes >= p50) OR (DstSubnet != servers) OR (SrcPortClass != well_known)
(Bytes > p25) OR (DstSubnet != servers) OR (SrcSubnet != servers)
(DstPortClass = well_known) OR (DstSubnet != servers) OR (SrcSubnet != servers)
(DstSubnet != servers) OR (Duration < p75) OR (SrcSubnet != servers)
(DstSubnet != servers) OR (Duration <= p25) OR (SrcSubnet != servers)
(DstSubnet != servers) OR (Duration <= p75) OR (SrcSubnet != servers)
(DstSubnet != servers) OR (Packets < p75) OR (SrcSubnet != servers)
(DstSubnet != servers) OR (Packets < p90) OR (SrcSubnet != servers)
(DstSubnet != servers) OR (Packets <= p75) OR (SrcSubnet != servers)
(DstSubnet != servers) OR (SrcPortClass != registered) OR (SrcSubnet != servers)
(DstSubnet != servers) OR (SrcPortClass != dynamic) OR (SrcSubnet != servers)
(DstSubnet != servers) OR (SrcPortClass = well_known) OR (SrcSubnet != servers)
(DstSubnet != servers) OR (SrcSubnet != servers) OR (SrcSubnet != management)
(DstSubnet != servers) OR (SrcSubnet != servers) OR (SrcSubnet != developer)
(Bytes > p50) OR (DstSubnet != servers) OR (Packets <= p25) OR (SrcSubnet != servers)
(Bytes > p75) OR (DstSubnet != servers) OR (Packets <= p25) OR (SrcSubnet != servers)
(Bytes >= p50) OR (DstSubnet != servers) OR (Packets <= p25) OR (SrcSubnet != servers)
(Bytes >= p75) OR (DstSubnet != servers) OR (Packets <= p25) OR (SrcSubnet != servers)
(Bytes < p50) OR (Bytes > p50) OR (DstSubnet != servers) OR (SrcSubnet != servers)
(Bytes <= p50) OR (Bytes >= p50) OR (DstSubnet != servers) OR (SrcSubnet != servers)
(Bytes > p50) OR (DstSubnet != servers) OR (Duration < p75)
(Bytes > p25) OR (DstSubnet != servers) OR (Duration < p75)
(Bytes >= p50) OR (DstSubnet != servers) OR (Duration < p75)
(DstPortClass = well_known) OR (DstSubnet != servers) OR (Duration < p75)
(DstSubnet != servers) OR (Duration < p75) OR (Duration > p25)
(DstSubnet != servers) OR (Duration < p75) OR (Duration > p75)
(DstSubnet != servers) OR (Duration < p75) OR (Packets > p25)
(DstSubnet != servers) OR (Duration < p75) OR (Packets >= p75)
(DstSubnet != servers) OR (Duration < p75) OR (SrcSubnet != management)
(DstSubnet != servers) OR (Duration < p75) OR (SrcSubnet = developer)
(Bytes > p75) OR (DstSubnet != servers) OR (Duration < p75) OR (Duration > p90)
(Bytes > p75) OR (DstSubnet != servers) OR (Duration < p75) OR (Duration >= p90)
(Bytes > p75) OR (DstSubnet != servers) OR (Duration < p75) OR (SrcPortClass != registered)
(Bytes > p75) OR (DstSubnet != servers) OR (Duration < p75) OR (SrcPortClass = dynamic)
(Bytes >= p75) OR (DstSubnet != servers) OR (Duration < p75) OR (Duration > p90)
(Bytes >= p75) OR (DstSubnet != servers) OR (Duration < p75) OR (Duration >= p90)
(Bytes >= p75) OR (DstSubnet != servers) OR (Duration < p75) OR (SrcPortClass != registered)
(Bytes >= p75) OR (DstSubnet != servers) OR (Duration < p75) OR (SrcPortClass = dynamic)
(Bytes < p75) OR (DstSubnet != servers) OR (Duration < p75) OR (Packets > p75)
(Bytes <= p75) OR (DstSubnet != servers) OR (Duration < p75) OR (Packets > p75)
(DstSubnet != servers) OR (Duration < p75) OR (Duration > p90) OR (Packets > p75)
(DstSubnet != servers) OR (Duration < p75) OR (Duration >= p90) OR (Packets > p75)
(DstSubnet != servers) OR (Duration < p75) OR (Packets > p75) OR (SrcPortClass != registered)
(DstSubnet != servers) OR (Duration < p75) OR (Packets > p75) OR (SrcPortClass = dynamic)
(Bytes < p75) OR (DstSubnet != servers) OR (Duration < p75) OR (Packets >= p90)
(Bytes <= p75) OR (DstSubnet != servers) OR (Duration < p75) OR (Packets >= p90)
(DstSubnet != servers) OR (Duration < p75) OR (Duration > p90) OR (Packets >= p90)
(DstSubnet != servers) OR (Duration < p75) OR (Duration >= p90) OR (Packets >= p90)
(DstSubnet != servers) OR (Duration < p75) OR (Packets <= p75) OR (Packets >= p90)
(DstSubnet != servers) OR (Duration < p75) OR (Packets >= p90) OR (SrcPortClass != registered)
(DstSubnet != servers) OR (Duration < p75) OR (Packets >= p90) OR (SrcPortClass = dynamic)
(DstSubnet != servers) OR (Duration < p75) OR (Packets > p90) OR (SrcPortClass != registered)
(DstSubnet != servers) OR (Duration < p75) OR (SrcPortClass != registered) OR (SrcPortClass != dynamic)
(DstSubnet != servers) OR (Duration < p75) OR (Packets > p90) OR (SrcPortClass = dynamic)
(DstSubnet != servers) OR (Duration < p75) OR (SrcPortClass = registered) OR (SrcPortClass = dynamic)
(Bytes < p75) OR (Bytes > p90) OR (DstSubnet != servers) OR (Duration < p75) OR (Packets > p90)
(Bytes < p75) OR (Bytes >= p90) OR (DstSubnet != servers) OR (Duration < p75) OR (Packets > p90)
(Bytes <= p75) OR (Bytes > p90) OR (DstSubnet != servers) OR (Duration < p75) OR (Packets > p90)
(Bytes <= p75) OR (Bytes >= p90) OR (DstSubnet != servers) OR (Duration < p75) OR (Packets > p90)
(Bytes > p90) OR (DstSubnet != servers) OR (Duration < p75) OR (Duration > p90) OR (Packets > p90)
(Bytes >= p90) OR (DstSubnet != servers) OR (Duration < p75) OR (Duration > p90) OR (Packets > p90)
(Bytes > p90) OR (DstSubnet != servers) OR (Duration < p75) OR (Duration >= p90) OR (Packets > p90)
(Bytes >= p90) OR (DstSubnet != servers) OR (Duration < p75) OR (Duration >= p90) OR (Packets > p90)
(Bytes > p90) OR (DstSubnet != servers) OR (Duration < p75) OR (Packets < p90) OR (Packets > p90)
(Bytes >= p90) OR (DstSubnet != servers) OR (Duration < p75) OR (Packets < p90) OR (Packets > p90)
(Bytes > p90) OR (DstSubnet != servers) OR (Duration < p75) OR (Packets <= p75) OR (Packets > p90)
(Bytes >= p90) OR (DstSubnet != servers) OR (Duration < p75) OR (Packets <= p75) OR (Packets > p90)
(Bytes > p50) OR (DstSubnet != servers) OR (Duration <= p75)
(Bytes > p25) OR (DstSubnet != servers) OR (Duration <= p75)
(Bytes >= p50) OR (DstSubnet != servers) OR (Duration <= p75)
(DstPortClass = well_known) OR (DstSubnet != servers) OR (Duration <= p75)
(DstSubnet != servers) OR (Duration <= p75) OR (Duration > p25)
(DstSubnet != servers) OR (Duration <= p75) OR (Duration >= p75)
(DstSubnet != servers) OR (Duration <= p75) OR (Packets > p25)
(DstSubnet != servers) OR (Duration <= p75) OR (Packets >= p75)
(DstSubnet != servers) OR (Duration <= p75) OR (SrcSubnet != management)
(DstSubnet != servers) OR (Duration <= p75) OR (SrcSubnet = developer)
(Bytes > p75) OR (DstSubnet != servers) OR (Duration <= p75) OR (Duration > p90)
(Bytes > p75) OR (DstSubnet != servers) OR (Duration <= p75) OR (Duration >= p90)
(Bytes > p75) OR (DstSubnet != servers) OR (Duration <= p75) OR (SrcPortClass != registered)
(Bytes > p75) OR (DstSubnet != servers) OR (Duration <= p75) OR (SrcPortClass = dynamic)
(Bytes >= p75) OR (DstSubnet != servers) OR (Duration <= p75) OR (Duration > p90)
(Bytes >= p75) OR (DstSubnet != servers) OR (Duration <= p75) OR (Duration >= p90)
(Bytes >= p75) OR (DstSubnet != servers) OR (Duration <= p75) OR (SrcPortClass != registered)
(Bytes >= p75) OR (DstSubnet != servers) OR (Duration <= p75) OR (SrcPortClass = dynamic)
(Bytes < p75) OR (DstSubnet != servers) OR (Duration <= p75) OR (Packets > p75)
(Bytes <= p75) OR (DstSubnet != servers) OR (Duration <= p75) OR (Packets > p75)
(DstSubnet != servers) OR (Duration <= p75) OR (Duration > p90) OR (Packets > p75)
(DstSubnet != servers) OR (Duration <= p75) OR (Duration >= p90) OR (Packets > p75)
(DstSubnet != servers) OR (Duration <= p75) OR (Packets > p75) OR (SrcPortClass != registered)
(DstSubnet != servers) OR (Duration <= p75) OR (Packets > p75) OR (SrcPortClass = dynamic)
(Bytes < p75) OR (DstSubnet != servers) OR (Duration <= p75) OR (Packets >= p90)
(Bytes <= p75) OR (DstSubnet != servers) OR (Duration <= p75) OR (Packets >= p90)
(DstSubnet != servers) OR (Duration <= p75) OR (Duration > p90) OR (Packets >= p90)
(DstSubnet != servers) OR (Duration <= p75) OR (Duration >= p90) OR (Packets >= p90)
(DstSubnet != servers) OR (Duration <= p75) OR (Packets <= p75) OR (Packets >= p90)
(DstSubnet != servers) OR (Duration <= p75) OR (Packets >= p90) OR (SrcPortClass != registered)
(DstSubnet != servers) OR (Duration <= p75) OR (Packets >= p90) OR (SrcPortClass = dynamic)
(DstSubnet != servers) OR (Duration <= p75) OR (Packets > p90) OR (SrcPortClass != registered)
(DstSubnet != servers) OR (Duration <= p75) OR (SrcPortClass != registered) OR (SrcPortClass != dynamic)
(DstSubnet != servers) OR (Duration <= p75) OR (Packets > p90) OR (SrcPortClass = dynamic)
(DstSubnet != servers) OR (Duration <= p75) OR (SrcPortClass = registered) OR (SrcPortClass = dynamic)
(Bytes < p75) OR (Bytes > p90) OR (DstSubnet != servers) OR (Duration <= p75) OR (Packets > p90)
(Bytes < p75) OR (Bytes >= p90) OR (DstSubnet != servers) OR (Duration <= p75) OR (Packets > p90)
(Bytes <= p75) OR (Bytes > p90) OR (DstSubnet != servers) OR (Duration <= p75) OR (Packets > p90)
(Bytes <= p75) OR (Bytes >= p90) OR (DstSubnet != servers) OR (Duration <= p75) OR (Packets > p90)
(Bytes > p90) OR (DstSubnet != servers) OR (Duration <= p75) OR (Duration > p90) OR (Packets > p90)
(Bytes >= p90) OR (DstSubnet != servers) OR (Duration <= p75) OR (Duration > p90) OR (Packets > p90)
(Bytes > p90) OR (DstSubnet != servers) OR (Duration <= p75) OR (Duration >= p90) OR (Packets > p90)
(Bytes >= p90) OR (DstSubnet != servers) OR (Duration <= p75) OR (Duration >= p90) OR (Packets > p90)
(Bytes > p90) OR (DstSubnet != servers) OR (Duration <= p75) OR (Packets < p90) OR (Packets > p90)
(Bytes >= p90) OR (DstSubnet != servers) OR (Duration <= p75) OR (Packets < p90) OR (Packets > p90)
(Bytes > p90) OR (DstSubnet != servers) OR (Duration <= p75) OR (Packets <= p75) OR (Packets > p90)
(Bytes >= p90) OR (DstSubnet != servers) OR (Duration <= p75) OR (Packets <= p75) OR (Packets > p90)
(Bytes > p50) OR (DstSubnet != servers) OR (Packets < p90)
(Bytes > p75) OR (DstSubnet != servers) OR (Packets < p90)
(Bytes > p25) OR (DstSubnet != servers) OR (Packets < p90)
(Bytes >= p50) OR (DstSubnet != servers) OR (Packets < p90)
(Bytes >= p75) OR (DstSubnet != servers) OR (Packets < p90)
(DstPortClass = well_known) OR (DstSubnet != servers) OR (Packets < p90)
(DstSubnet != servers) OR (Duration > p25) OR (Packets < p90)
(DstSubnet != servers) OR (Packets < p90) OR (Packets > p25)
(DstSubnet != servers) OR (Packets < p90) OR (Packets > p75)
(DstSubnet != servers) OR (Packets < p90) OR (Packets >= p75)
(DstSubnet != servers) OR (Packets < p90) OR (SrcSubnet != management)
(DstSubnet != servers) OR (Packets < p90) OR (SrcSubnet = developer)
(DstSubnet != servers) OR (Packets < p90) OR (SrcPortClass != registered) OR (SrcPortClass != dynamic)
(DstSubnet != servers) OR (Packets < p90) OR (SrcPortClass = registered) OR (SrcPortClass = dynamic)
(Bytes > p50) OR (DstSubnet != servers) OR (Packets <= p75)
(Bytes > p75) OR (DstSubnet != servers) OR (Packets <= p75)
(Bytes > p25) OR (DstSubnet != servers) OR (Packets <= p75)
(Bytes >= p50) OR (DstSubnet != servers) OR (Packets <= p75)
(Bytes >= p75) OR (DstSubnet != servers) OR (Packets <= p75)
(DstSubnet != servers) OR (Duration > p25) OR (Packets <= p75)
(DstSubnet != servers) OR (Packets <= p75) OR (Packets > p25)
(DstSubnet != servers) OR (Packets <= p75) OR (Packets >= p75)
(DstPortClass = well_known) OR (DstPortClass = http) OR (DstSubnet != servers) OR (Packets <= p75)
(DstPortClass = well_known) OR (DstSubnet != servers) OR (Packets <= p75) OR (SrcPortClass != registered)
(DstPortClass = well_known) OR (DstSubnet != servers) OR (Packets <= p75) OR (SrcPortClass = dynamic)
(DstPortClass = well_known) OR (DstSubnet != servers) OR (Packets <= p75) OR (SrcSubnet != developer)
(DstPortClass = well_known) OR (DstSubnet != servers) OR (Packets <= p75) OR (SrcSubnet = management)
(DstPortClass != well_known) OR (DstSubnet != servers) OR (Packets <= p75) OR (Packets >= p90)
(DstPortClass = http) OR (DstSubnet != servers) OR (Packets <= p75) OR (Packets >= p90)
(DstSubnet != servers) OR (Packets <= p75) OR (Packets >= p90) OR (SrcPortClass != registered)
(DstSubnet != servers) OR (Packets <= p75) OR (Packets >= p90) OR (SrcPortClass = dynamic)
(DstSubnet != servers) OR (Packets <= p75) OR (Packets >= p90) OR (SrcSubnet != developer)
(DstSubnet != servers) OR (Packets <= p75) OR (Packets >= p90) OR (SrcSubnet = management)
(DstPortClass != well_known) OR (DstSubnet != servers) OR (Packets <= p75) OR (SrcSubnet != management)
(DstPortClass = http) OR (DstSubnet != servers) OR (Packets <= p75) OR (SrcSubnet != management)
(DstSubnet != servers) OR (Packets <= p75) OR (SrcPortClass != registered) OR (SrcSubnet != management)
(DstSubnet != servers) OR (Packets <= p75) OR (SrcPortClass = dynamic) OR (SrcSubnet != management)
(DstSubnet != servers) OR (Packets <= p75) OR (SrcSubnet != management) OR (SrcSubnet != developer)
(DstPortClass != well_known) OR (DstSubnet != servers) OR (Packets <= p75) OR (SrcSubnet = developer)
(DstPortClass = http) OR (DstSubnet != servers) OR (Packets <= p75) OR (SrcSubnet = developer)
(DstSubnet != servers) OR (Packets <= p75) OR (SrcPortClass != registered) OR (SrcSubnet = developer)
(DstSubnet != servers) OR (Packets <= p75) OR (SrcPortClass = dynamic) OR (SrcSubnet = developer)
(DstSubnet != servers) OR (Packets <= p75) OR (SrcSubnet = management) OR (SrcSubnet = developer)
(DstSubnet != servers) OR (Packets <= p75) OR (SrcPortClass != registered) OR (SrcPortClass != dynamic)
(DstSubnet != servers) OR (Packets <= p75) OR (SrcPortClass = registered) OR (SrcPortClass = dynamic)
(Bytes < p75) OR (DstPortClass = well_known) OR (DstPortClass = http) OR (DstSubnet != servers)
(Bytes < p75) OR (DstPortClass = well_known) OR (DstSubnet != servers) OR (Duration > p25)
(Bytes < p75) OR (DstPortClass = well_known) OR (DstSubnet != servers) OR (Packets > p75)
(Bytes < p75) OR (DstPortClass = well_known) OR (DstSubnet != servers) OR (Packets >= p75)
(Bytes < p75) OR (DstPortClass = well_known) OR (DstSubnet != servers) OR (SrcPortClass != registered)
(Bytes < p75) OR (DstPortClass = well_known) OR (DstSubnet != servers) OR (SrcPortClass = dynamic)
(Bytes < p75) OR (DstPortClass = well_known) OR (DstSubnet != servers) OR (SrcSubnet != developer)
(Bytes < p75) OR (DstPortClass = well_known) OR (DstSubnet != servers) OR (SrcSubnet = management)
(Bytes <= p50) OR (Bytes > p75) OR (DstPortClass = well_known) OR (DstSubnet != servers)
(Bytes <= p50) OR (Bytes > p25) OR (DstPortClass = well_known) OR (DstSubnet != servers)
(Bytes <= p50) OR (Bytes >= p50) OR (DstPortClass = well_known) OR (DstSubnet != servers)
(Bytes <= p50) OR (Bytes >= p75) OR (DstPortClass = well_known) OR (DstSubnet != servers)
(Bytes <= p50) OR (DstPortClass = well_known) OR (DstPortClass = http) OR (DstSubnet != servers)
(Bytes <= p50) OR (DstPortClass = well_known) OR (DstSubnet != servers) OR (Duration > p25)
(Bytes <= p50) OR (DstPortClass = well_known) OR (DstSubnet != servers) OR (Packets > p25)
(Bytes <= p50) OR (DstPortClass = well_known) OR (DstSubnet != servers) OR (Packets > p75)
(Bytes <= p50) OR (DstPortClass = well_known) OR (DstSubnet != servers) OR (Packets >= p75)
(Bytes <= p50) OR (DstPortClass = well_known) OR (DstSubnet != servers) OR (SrcPortClass != registered)
(Bytes <= p50) OR (DstPortClass = well_known) OR (DstSubnet != servers) OR (SrcPortClass = dynamic)
(Bytes <= p50) OR (DstPortClass = well_known) OR (DstSubnet != servers) OR (SrcSubnet != developer)
(Bytes <= p50) OR (DstPortClass = well_known) OR (DstSubnet != servers) OR (SrcSubnet = management)
(Bytes <= p75) OR (DstPortClass = well_known) OR (DstPortClass = http) OR (DstSubnet != servers)
(Bytes <= p75) OR (DstPortClass = well_known) OR (DstSubnet != servers) OR (Duration > p25)
(Bytes <= p75) OR (DstPortClass = well_known) OR (DstSubnet != servers) OR (Packets > p75)
(Bytes <= p75) OR (DstPortClass = well_known) OR (DstSubnet != servers) OR (Packets >= p75)
(Bytes <= p75) OR (DstPortClass = well_known) OR (DstSubnet != servers) OR (SrcPortClass != registered)
(Bytes <= p75) OR (DstPortClass = well_known) OR (DstSubnet != servers) OR (SrcPortClass = dynamic)
(Bytes <= p75) OR (DstPortClass = well_known) OR (DstSubnet != servers) OR (SrcSubnet != developer)
(Bytes <= p75) OR (DstPortClass = well_known) OR (DstSubnet != servers) OR (SrcSubnet = management)
(Bytes < p50) OR (Bytes > p25) OR (DstPortClass = well_known) OR (DstSubnet != servers)
(Bytes > p25) OR (DstPortClass = well_known) OR (DstPortClass = http) OR (DstSubnet != servers)
(Bytes > p25) OR (DstPortClass = well_known) OR (DstSubnet != servers) OR (Duration <= p25)
(Bytes > p25) OR (DstPortClass = well_known) OR (DstSubnet != servers) OR (Packets <= p25)
(Bytes > p25) OR (DstPortClass = well_known) OR (DstSubnet != servers) OR (SrcPortClass != dynamic)
(Bytes > p25) OR (DstPortClass = well_known) OR (DstSubnet != servers) OR (SrcPortClass = registered)
(Bytes > p25) OR (DstPortClass = well_known) OR (DstSubnet != servers) OR (SrcSubnet != management)
(Bytes > p25) OR (DstPortClass = well_known) OR (DstSubnet != servers) OR (SrcSubnet = developer)
(Bytes > p75) OR (DstPortClass = well_known) OR (DstSubnet != servers) OR (Packets < p75)
(Bytes >= p75) OR (DstPortClass = well_known) OR (DstSubnet != servers) OR (Packets < p75)
(DstPortClass = well_known) OR (DstPortClass = http) OR (DstSubnet != servers) OR (Packets < p75)
(DstPortClass = well_known) OR (DstSubnet != servers) OR (Packets < p75) OR (Packets > p75)
(DstPortClass = well_known) OR (DstSubnet != servers) OR (Packets < p75) OR (SrcPortClass != registered)
(DstPortClass = well_known) OR (DstSubnet != servers) OR (Packets < p75) OR (SrcPortClass = dynamic)
(DstPortClass = well_known) OR (DstSubnet != servers) OR (Packets < p75) OR (SrcSubnet != developer)
(DstPortClass = well_known) OR (DstSubnet != servers) OR (Packets < p75) OR (SrcSubnet = management)
(DstPortClass = well_known) OR (DstPortClass = http) OR (DstSubnet != servers) OR (SrcPortClass != registered)
(DstPortClass = well_known) OR (DstSubnet != servers) OR (SrcPortClass != registered) OR (SrcPortClass != dynamic)
(DstPortClass = well_known) OR (DstSubnet != servers) OR (SrcPortClass != registered) OR (SrcSubnet != management)
(DstPortClass = well_known) OR (DstSubnet != servers) OR (SrcPortClass != registered) OR (SrcSubnet = developer)
(Bytes <= p25) OR (Bytes >= p50) OR (DstPortClass = well_known) OR (DstSubnet != servers) OR (SrcPortClass != registered)
(Bytes <= p25) OR (DstPortClass = well_known) OR (DstSubnet != servers) OR (Duration > p25) OR (SrcPortClass != registered)
(Bytes <= p25) OR (DstPortClass = well_known) OR (DstSubnet != servers) OR (Packets > p25) OR (SrcPortClass != registered)
(Bytes >= p50) OR (DstPortClass = well_known) OR (DstSubnet != servers) OR (Packets <= p25) OR (SrcPortClass != registered)
(DstPortClass = well_known) OR (DstSubnet != servers) OR (Duration > p25) OR (Packets <= p25) OR (SrcPortClass != registered)
(DstPortClass = well_known) OR (DstPortClass = http) OR (DstSubnet != servers) OR (SrcSubnet != management)
(DstPortClass = well_known) OR (DstSubnet != servers) OR (Packets > p25) OR (SrcSubnet != management)
(DstPortClass = well_known) OR (DstSubnet != servers) OR (SrcPortClass = dynamic) OR (SrcSubnet != management)
(DstPortClass = well_known) OR (DstSubnet != servers) OR (SrcSubnet != management) OR (SrcSubnet != developer)
(Bytes < p50) OR (Bytes > p50) OR (DstPortClass = well_known) OR (DstSubnet != servers) OR (SrcSubnet != management)
(Bytes > p50) OR (DstPortClass = well_known) OR (DstSubnet != servers) OR (Duration <= p25) OR (SrcSubnet != management)
(Bytes < p50) OR (Bytes > p75) OR (DstPortClass = well_known) OR (DstSubnet != servers) OR (SrcSubnet != management)
(Bytes > p75) OR (DstPortClass = well_known) OR (DstSubnet != servers) OR (Duration <= p25) OR (SrcSubnet != management)
(Bytes < p50) OR (Bytes >= p75) OR (DstPortClass = well_known) OR (DstSubnet != servers) OR (SrcSubnet != management)
(Bytes >= p75) OR (DstPortClass = well_known) OR (DstSubnet != servers) OR (Duration <= p25) OR (SrcSubnet != management)
(Bytes < p50) OR (DstPortClass = well_known) OR (DstSubnet != servers) OR (Packets > p75) OR (SrcSubnet != management)
(DstPortClass = well_known) OR (DstSubnet != servers) OR (Duration <= p25) OR (Packets > p75) OR (SrcSubnet != management)
(Bytes < p50) OR (DstPortClass = well_known) OR (DstSubnet != servers) OR (Packets >= p75) OR (SrcSubnet != management)
(DstPortClass = well_known) OR (DstSubnet != servers) OR (Duration <= p25) OR (Packets >= p75) OR (SrcSubnet != management)
(Bytes < p50) OR (DstPortClass = well_known) OR (DstPortClass = http) OR (DstSubnet != servers)
(Bytes < p50) OR (DstPortClass = well_known) OR (DstSubnet != servers) OR (Duration > p25)
(Bytes < p50) OR (DstPortClass = well_known) OR (DstSubnet != servers) OR (Packets > p25)
(Bytes < p50) OR (DstPortClass = well_known) OR (DstSubnet != servers) OR (SrcPortClass = registered) OR (SrcPortClass = dynamic)
(Bytes < p50) OR (DstPortClass = well_known) OR (DstSubnet != servers) OR (SrcPortClass = dynamic) OR (SrcSubnet = developer)
(Bytes < p50) OR (Bytes > p50) OR (DstPortClass = well_known) OR (DstSubnet != servers) OR (SrcSubnet = developer)
(Bytes < p50) OR (Bytes > p75) OR (DstPortClass = well_known) OR (DstSubnet != servers) OR (SrcSubnet = developer)
(Bytes < p50) OR (Bytes >= p75) OR (DstPortClass = well_known) OR (DstSubnet != servers) OR (SrcSubnet = developer)
(Bytes < p50) OR (DstPortClass = well_known) OR (DstSubnet != servers) OR (Packets > p75) OR (SrcSubnet = developer)
(Bytes < p50) OR (DstPortClass = well_known) OR (DstSubnet != servers) OR (Packets >= p75) OR (SrcSubnet = developer)
(Bytes < p50) OR (DstPortClass = well_known) OR (DstSubnet != servers) OR (SrcSubnet = management) OR (SrcSubnet = developer)
(Bytes >= p50) OR (DstPortClass = well_known) OR (DstSubnet != servers) OR (Duration <= p25)
(DstPortClass = well_known) OR (DstPortClass = http) OR (DstSubnet != servers) OR (Duration <= p25)
(DstPortClass = well_known) OR (DstSubnet != servers) OR (Duration <= p25) OR (Packets > p25)
(DstPortClass = well_known) OR (DstSubnet != servers) OR (Duration <= p25) OR (SrcPortClass = registered) OR (SrcPortClass = dynamic)
(DstPortClass = well_known) OR (DstSubnet != servers) OR (Duration <= p25) OR (SrcPortClass = dynamic) OR (SrcSubnet = developer)
(Bytes > p50) OR (DstPortClass = well_known) OR (DstSubnet != servers) OR (Duration <= p25) OR (SrcSubnet = developer)
(Bytes > p75) OR (DstPortClass = well_known) OR (DstSubnet != servers) OR (Duration <= p25) OR (SrcSubnet = developer)
(Bytes >= p75) OR (DstPortClass = well_known) OR (DstSubnet != servers) OR (Duration <= p25) OR (SrcSubnet = developer)
(DstPortClass = well_known) OR (DstSubnet != servers) OR (Duration <= p25) OR (Packets > p75) OR (SrcSubnet = developer)
(DstPortClass = well_known) OR (DstSubnet != servers) OR (Duration <= p25) OR (Packets >= p75) OR (SrcSubnet = developer)
(DstPortClass = well_known) OR (DstSubnet != servers) OR (Duration <= p25) OR (SrcSubnet = management) OR (SrcSubnet = developer)
(DstPortClass = well_known) OR (DstPortClass = http) OR (DstSubnet != servers) OR (SrcSubnet != developer)
(Bytes <= p25) OR (Bytes >= p50) OR (DstPortClass = well_known) OR (DstSubnet != servers) OR (SrcSubnet != developer)
(Bytes >= p50) OR (DstPortClass = well_known) OR (DstSubnet != servers) OR (Packets <= p25) OR (SrcSubnet != developer)
(Bytes >= p50) OR (DstPortClass = well_known) OR (DstSubnet != servers) OR (SrcPortClass != dynamic) OR (SrcSubnet != developer)
(Bytes >= p50) OR (DstPortClass = well_known) OR (DstSubnet != servers) OR (SrcPortClass = registered) OR (SrcSubnet != developer)
(Bytes <= p25) OR (DstPortClass = well_known) OR (DstSubnet != servers) OR (Duration > p25) OR (SrcSubnet != developer)
(DstPortClass = well_known) OR (DstSubnet != servers) OR (Duration > p25) OR (Packets <= p25) OR (SrcSubnet != developer)
(DstPortClass = well_known) OR (DstSubnet != servers) OR (Duration > p25) OR (SrcPortClass != dynamic) OR (SrcSubnet != developer)
(DstPortClass = well_known) OR (DstSubnet != servers) OR (Duration > p25) OR (SrcPortClass = registered) OR (SrcSubnet != developer)
(Bytes <= p25) OR (DstPortClass = well_known) OR (DstSubnet != servers) OR (Packets > p25) OR (SrcSubnet != developer)
(DstPortClass = well_known) OR (DstSubnet != servers) OR (Packets > p25) OR (SrcPortClass = registered) OR (SrcSubnet != developer)
(DstPortClass = well_known) OR (DstSubnet != servers) OR (SrcPortClass = registered) OR (SrcPortClass = dynamic) OR (SrcSubnet != developer)
(DstPortClass = well_known) OR (DstPortClass = http) OR (DstSubnet != servers) OR (SrcPortClass != dynamic)
(DstPortClass = well_known) OR (DstSubnet != servers) OR (Packets > p25) OR (SrcPortClass != dynamic)
(Bytes >= p50) OR (DstPortClass = well_known) OR (DstSubnet != servers) OR (SrcPortClass != dynamic) OR (SrcSubnet = management) OR (SrcSubnet = office)
(DstPortClass = well_known) OR (DstSubnet != servers) OR (Duration > p25) OR (SrcPortClass != dynamic) OR (SrcSubnet = management) OR (SrcSubnet = office)
(DstPortClass = well_known) OR (DstSubnet != servers) OR (SrcPortClass != dynamic) OR (SrcSubnet = management) OR (SrcSubnet = office) OR (SrcSubnet = developer)
(DstPortClass = well_known) OR (DstPortClass = http) OR (DstSubnet != servers) OR (Packets <= p25)
(Bytes >= p50) OR (DstPortClass = well_known) OR (DstSubnet != servers) OR (Packets <= p25) OR (SrcPortClass = dynamic)
(Bytes >= p50) OR (DstPortClass = well_known) OR (DstSubnet != servers) OR (Packets <= p25) OR (SrcSubnet = management) OR (SrcSubnet = office)
(DstPortClass = well_known) OR (DstSubnet != servers) OR (Duration > p25) OR (Packets <= p25) OR (SrcPortClass = dynamic)
(DstPortClass = well_known) OR (DstSubnet != servers) OR (Duration > p25) OR (Packets <= p25) OR (SrcSubnet = management) OR (SrcSubnet = office)
(DstPortClass = well_known) OR (DstSubnet != servers) OR (Packets <= p25) OR (SrcPortClass = dynamic) OR (SrcSubnet = developer)
(DstPortClass = well_known) OR (DstSubnet != servers) OR (Packets <= p25) OR (SrcSubnet = management) OR (SrcSubnet = office) OR (SrcSubnet = developer)
(DstPortClass = well_known) OR (DstSubnet != servers) OR (Packets <= p25) OR (SrcPortClass = registered) OR (SrcPortClass = dynamic)
(DstPortClass = well_known) OR (DstPortClass = http) OR (DstSubnet != servers) OR (SrcPortClass = dns)
(Bytes <= p25) OR (DstPortClass = well_known) OR (DstSubnet != servers) OR (Packets > p25) OR (SrcPortClass = dns)
(DstPortClass = well_known) OR (DstSubnet != servers) OR (Packets > p25) OR (SrcPortClass = dns) OR (SrcPortClass = registered)
(DstPortClass = well_known) OR (DstSubnet != servers) OR (Packets > p25) OR (SrcPortClass = dns) OR (SrcSubnet = developer)
(Bytes <= p25) OR (Bytes >= p50) OR (DstPortClass = well_known) OR (DstSubnet != servers) OR (SrcPortClass = dns) OR (SrcPortClass = dynamic)
(Bytes <= p25) OR (Bytes >= p50) OR (DstPortClass = well_known) OR (DstSubnet != servers) OR (SrcPortClass = dns) OR (SrcSubnet = management) OR (SrcSubnet = office)
(Bytes >= p50) OR (DstPortClass = well_known) OR (DstSubnet != servers) OR (SrcPortClass = dns) OR (SrcPortClass = registered) OR (SrcSubnet = management) OR (SrcSubnet = office)
(Bytes <= p25) OR (DstPortClass = well_known) OR (DstSubnet != servers) OR (Duration > p25) OR (SrcPortClass = dns) OR (SrcPortClass = dynamic)
(Bytes <= p25) OR (DstPortClass = well_known) OR (DstSubnet != servers) OR (Duration > p25) OR (SrcPortClass = dns) OR (SrcSubnet = management) OR (SrcSubnet = office)
(DstPortClass = well_known) OR (DstSubnet != servers) OR (Duration > p25) OR (SrcPortClass = dns) OR (SrcPortClass = registered) OR (SrcSubnet = management) OR (SrcSubnet = office)
(DstPortClass = well_known) OR (DstSubnet != servers) OR (SrcPortClass = dns) OR (SrcPortClass = dynamic) OR (SrcSubnet = developer)
(DstPortClass = well_known) OR (DstSubnet != servers) OR (SrcPortClass = dns) OR (SrcSubnet = management) OR (SrcSubnet = office) OR (SrcSubnet = developer)
(DstPortClass = well_known) OR (DstSubnet != servers) OR (SrcPortClass = dns) OR (SrcPortClass = registered) OR (SrcPortClass = dynamic)
(DstPortClass = well_known) OR (DstPortClass = http) OR (DstSubnet != servers) OR (SrcSubnet = dns)
(Bytes <= p25) OR (DstPortClass = well_known) OR (DstSubnet != servers) OR (Packets > p25) OR (SrcSubnet = dns)
(DstPortClass = well_known) OR (DstSubnet != servers) OR (Packets > p25) OR (SrcPortClass = registered) OR (SrcSubnet = dns)
(DstPortClass = well_known) OR (DstSubnet != servers) OR (Packets > p25) OR (SrcSubnet = developer) OR (SrcSubnet = dns)
(Bytes <= p25) OR (Bytes >= p50) OR (DstPortClass = well_known) OR (DstSubnet != servers) OR (SrcPortClass = dynamic) OR (SrcSubnet = dns)
(Bytes <= p25) OR (Bytes >= p50) OR (DstPortClass = well_known) OR (DstSubnet != servers) OR (SrcSubnet = management) OR (SrcSubnet = office) OR (SrcSubnet = dns)
(Bytes >= p50) OR (DstPortClass = well_known) OR (DstSubnet != servers) OR (SrcPortClass = registered) OR (SrcSubnet = management) OR (SrcSubnet = office) OR (SrcSubnet = dns)
(Bytes <= p25) OR (DstPortClass = well_known) OR (DstSubnet != servers) OR (Duration > p25) OR (SrcPortClass = dynamic) OR (SrcSubnet = dns)
(Bytes <= p25) OR (DstPortClass = well_known) OR (DstSubnet != servers) OR (Duration > p25) OR (SrcSubnet = management) OR (SrcSubnet = office) OR (SrcSubnet = dns)
(DstPortClass = well_known) OR (DstSubnet != servers) OR (Duration > p25) OR (SrcPortClass = registered) OR (SrcSubnet = management) OR (SrcSubnet = office) OR (SrcSubnet = dns)
(DstPortClass = well_known) OR (DstSubnet != servers) OR (SrcPortClass = dynamic) OR (SrcSubnet = developer) OR (SrcSubnet = dns)
(DstPortClass = well_known) OR (DstSubnet != servers) OR (SrcSubnet = management) OR (SrcSubnet = office) OR (SrcSubnet = developer) OR (SrcSubnet = dns)
(DstPortClass = well_known) OR (DstSubnet != servers) OR (SrcPortClass = registered) OR (SrcPortClass = dynamic) OR (SrcSubnet = dns)
(DstPortClass = well_known) OR (DstPortClass = registered) OR (DstPortClass = dynamic) OR (DstPortClass = http) OR (DstSubnet != servers)
(Bytes <= p25) OR (DstPortClass = well_known) OR (DstPortClass = registered) OR (DstPortClass = dynamic) OR (DstSubnet != servers) OR (Packets > p25)
(DstPortClass = well_known) OR (DstPortClass = registered) OR (DstPortClass = dynamic) OR (DstSubnet != servers) OR (Packets > p25) OR (SrcPortClass = registered)
(DstPortClass = well_known) OR (DstPortClass = registered) OR (DstPortClass = dynamic) OR (DstSubnet != servers) OR (Packets > p25) OR (SrcSubnet = developer)
(Bytes <= p25) OR (Bytes >= p50) OR (DstPortClass = well_known) OR (DstPortClass = registered) OR (DstPortClass = dynamic) OR (DstSubnet != servers) OR (SrcPortClass = dynamic)
(Bytes <= p25) OR (Bytes >= p50) OR (DstPortClass = well_known) OR (DstPortClass = registered) OR (DstPortClass = dynamic) OR (DstSubnet != servers) OR (SrcSubnet = management) OR (SrcSubnet = office)
(Bytes >= p50) OR (DstPortClass = well_known) OR (DstPortClass = registered) OR (DstPortClass = dynamic) OR (DstSubnet != servers) OR (SrcPortClass = registered) OR (SrcSubnet = management) OR (SrcSubnet = office)
(Bytes <= p25) OR (DstPortClass = well_known) OR (DstPortClass = registered) OR (DstPortClass = dynamic) OR (DstSubnet != servers) OR (Duration > p25) OR (SrcPortClass = dynamic)
(Bytes <= p25) OR (DstPortClass = well_known) OR (DstPortClass = registered) OR (DstPortClass = dynamic) OR (DstSubnet != servers) OR (Duration > p25) OR (SrcSubnet = management) OR (SrcSubnet = office)
(DstPortClass = well_known) OR (DstPortClass = registered) OR (DstPortClass = dynamic) OR (DstSubnet != servers) OR (Duration > p25) OR (SrcPortClass = registered) OR (SrcSubnet = management) OR (SrcSubnet = office)
(DstPortClass = well_known) OR (DstPortClass = registered) OR (DstPortClass = dynamic) OR (DstSubnet != servers) OR (SrcPortClass = dynamic) OR (SrcSubnet = developer)
(DstPortClass = well_known) OR (DstPortClass = registered) OR (DstPortClass = dynamic) OR (DstSubnet != servers) OR (SrcSubnet = management) OR (SrcSubnet = office) OR (SrcSubnet = developer)
(DstPortClass = well_known) OR (DstPortClass = registered) OR (DstPortClass = dynamic) OR (DstSubnet != servers) OR (SrcPortClass = registered) OR (SrcPortClass = dynamic)
(Bytes < p75) OR (Bytes > p50) OR (DstSubnet != servers)
(Bytes < p75) OR (Bytes > p75) OR (DstSubnet != servers)
(Bytes < p75) OR (Bytes > p25) OR (DstSubnet != servers)
(Bytes < p75) OR (Bytes >= p50) OR (DstSubnet != servers)
(Bytes < p75) OR (DstSubnet != servers) OR (Packets > p25)
(Bytes < p75) OR (DstPortClass != well_known) OR (DstSubnet != servers) OR (SrcSubnet != management)
(Bytes < p75) OR (DstPortClass = http) OR (DstSubnet != servers) OR (SrcSubnet != management)
(Bytes < p75) OR (DstSubnet != servers) OR (Duration > p25) OR (SrcSubnet != management)
(Bytes < p75) OR (DstSubnet != servers) OR (Packets > p75) OR (SrcSubnet != management)
(Bytes < p75) OR (DstSubnet != servers) OR (Packets >= p75) OR (SrcSubnet != management)
(Bytes < p75) OR (DstSubnet != servers) OR (SrcPortClass != registered) OR (SrcSubnet != management)
(Bytes < p75) OR (DstSubnet != servers) OR (SrcPortClass = dynamic) OR (SrcSubnet != management)
(Bytes < p75) OR (DstSubnet != servers) OR (SrcSubnet != management) OR (SrcSubnet != developer)
(Bytes < p75) OR (DstSubnet != servers) OR (Duration > p25) OR (SrcPortClass != registered)
(Bytes < p75) OR (DstSubnet != servers) OR (Duration > p25) OR (SrcPortClass != dynamic)
(Bytes < p75) OR (DstSubnet != servers) OR (Duration > p25) OR (SrcPortClass = well_known)
(Bytes < p75) OR (DstSubnet != servers) OR (Duration > p25) OR (SrcSubnet != developer)
(Bytes < p75) OR (DstSubnet != servers) OR (Duration > p25) OR (SrcSubnet = servers)
(Bytes < p75) OR (DstSubnet != servers) OR (Duration <= p25) OR (Packets > p75)
(Bytes < p75) OR (DstSubnet != servers) OR (Packets < p75) OR (Packets > p75)
(Bytes < p75) OR (DstSubnet != servers) OR (Packets > p75) OR (SrcPortClass != registered)
(Bytes < p75) OR (DstSubnet != servers) OR (Packets > p75) OR (SrcPortClass != dynamic)
(Bytes < p75) OR (DstSubnet != servers) OR (Packets > p75) OR (SrcPortClass = well_known)
(Bytes < p75) OR (DstSubnet != servers) OR (Packets > p75) OR (SrcSubnet != developer)
(Bytes < p75) OR (DstSubnet != servers) OR (Packets > p75) OR (SrcSubnet = servers)
(Bytes < p75) OR (DstSubnet != servers) OR (Duration <= p25) OR (Packets >= p75)
(Bytes < p75) OR (DstSubnet != servers) OR (Packets >= p75) OR (SrcPortClass != registered)
(Bytes < p75) OR (DstSubnet != servers) OR (Packets >= p75) OR (SrcPortClass != dynamic)
(Bytes < p75) OR (DstSubnet != servers) OR (Packets >= p75) OR (SrcPortClass = well_known)
(Bytes < p75) OR (DstSubnet != servers) OR (Packets >= p75) OR (SrcSubnet != developer)
(Bytes < p75) OR (DstSubnet != servers) OR (Packets >= p75) OR (SrcSubnet = servers)
(Bytes < p75) OR (DstSubnet != servers) OR (Packets >= p90) OR (SrcPortClass != registered)
(Bytes < p75) OR (DstSubnet != servers) OR (Packets >= p90) OR (SrcSubnet != developer)
(Bytes < p75) OR (DstPortClass != well_known) OR (DstSubnet != servers) OR (Duration <= p25) OR (Packets >= p90)
(Bytes < p75) OR (DstPortClass = http) OR (DstSubnet != servers) OR (Duration <= p25) OR (Packets >= p90)
(Bytes < p75) OR (DstSubnet != servers) OR (Duration <= p25) OR (Packets >= p90) OR (SrcPortClass = dynamic)
(Bytes < p75) OR (DstSubnet != servers) OR (Duration <= p25) OR (Packets >= p90) OR (SrcSubnet = management)
(Bytes < p75) OR (DstPortClass != well_known) OR (DstSubnet != servers) OR (Packets < p75) OR (Packets >= p90)
(Bytes < p75) OR (DstPortClass = http) OR (DstSubnet != servers) OR (Packets < p75) OR (Packets >= p90)
(Bytes < p75) OR (DstSubnet != servers) OR (Packets < p75) OR (Packets >= p90) OR (SrcPortClass = dynamic)
(Bytes < p75) OR (DstSubnet != servers) OR (Packets < p75) OR (Packets >= p90) OR (SrcSubnet = management)
(Bytes < p75) OR (DstPortClass != well_known) OR (DstSubnet != servers) OR (Packets >= p90) OR (SrcPortClass != dynamic)
(Bytes < p75) OR (DstPortClass = http) OR (DstSubnet != servers) OR (Packets >= p90) OR (SrcPortClass != dynamic)
(Bytes < p75) OR (DstSubnet != servers) OR (Packets >= p90) OR (SrcPortClass != dynamic) OR (SrcSubnet = management)
(Bytes < p75) OR (DstPortClass != well_known) OR (DstSubnet != servers) OR (Packets >= p90) OR (SrcPortClass = well_known)
(Bytes < p75) OR (DstPortClass = http) OR (DstSubnet != servers) OR (Packets >= p90) OR (SrcPortClass = well_known)
(Bytes < p75) OR (DstSubnet != servers) OR (Packets >= p90) OR (SrcPortClass = well_known) OR (SrcPortClass = dynamic)
(Bytes < p75) OR (DstSubnet != servers) OR (Packets >= p90) OR (SrcPortClass = well_known) OR (SrcSubnet = management)
(Bytes < p75) OR (DstPortClass != well_known) OR (DstSubnet != servers) OR (Packets >= p90) OR (SrcSubnet = servers)
(Bytes < p75) OR (DstPortClass = http) OR (DstSubnet != servers) OR (Packets >= p90) OR (SrcSubnet = servers)
(Bytes < p75) OR (DstSubnet != servers) OR (Packets >= p90) OR (SrcPortClass = dynamic) OR (SrcSubnet = servers)
(Bytes < p75) OR (DstSubnet != servers) OR (Packets >= p90) OR (SrcSubnet = servers) OR (SrcSubnet = management)
(Bytes < p75) OR (DstSubnet != servers) OR (SrcPortClass != registered) OR (SrcSubnet = developer)
(Bytes < p75) OR (DstPortClass != well_known) OR (DstSubnet != servers) OR (Duration <= p25) OR (SrcSubnet = developer)
(Bytes < p75) OR (DstPortClass = http) OR (DstSubnet != servers) OR (Duration <= p25) OR (SrcSubnet = developer)
(Bytes < p75) OR (DstSubnet != servers) OR (Duration <= p25) OR (SrcPortClass = dynamic) OR (SrcSubnet = developer)
(Bytes < p75) OR (DstSubnet != servers) OR (Duration <= p25) OR (SrcSubnet = management) OR (SrcSubnet = developer)
(Bytes < p75) OR (DstPortClass != well_known) OR (DstSubnet != servers) OR (SrcPortClass != dynamic) OR (SrcSubnet = developer)
(Bytes < p75) OR (DstPortClass = http) OR (DstSubnet != servers) OR (SrcPortClass != dynamic) OR (SrcSubnet = developer)
(Bytes < p75) OR (DstSubnet != servers) OR (SrcPortClass != dynamic) OR (SrcSubnet = management) OR (SrcSubnet = developer)
(Bytes < p75) OR (DstPortClass != well_known) OR (DstSubnet != servers) OR (SrcPortClass = well_known) OR (SrcSubnet = developer)
(Bytes < p75) OR (DstPortClass = http) OR (DstSubnet != servers) OR (SrcPortClass = well_known) OR (SrcSubnet = developer)
(Bytes < p75) OR (DstSubnet != servers) OR (SrcPortClass = well_known) OR (SrcPortClass = dynamic) OR (SrcSubnet = developer)
(Bytes < p75) OR (DstSubnet != servers) OR (SrcPortClass = well_known) OR (SrcSubnet = management) OR (SrcSubnet = developer)
(Bytes < p75) OR (DstPortClass != well_known) OR (DstSubnet != servers) OR (SrcSubnet = servers) OR (SrcSubnet = developer)
(Bytes < p75) OR (DstPortClass = http) OR (DstSubnet != servers) OR (SrcSubnet = servers) OR (SrcSubnet = developer)
(Bytes < p75) OR (DstSubnet != servers) OR (SrcPortClass = dynamic) OR (SrcSubnet = servers) OR (SrcSubnet = developer)
(Bytes < p75) OR (DstSubnet != servers) OR (SrcSubnet = servers) OR (SrcSubnet = management) OR (SrcSubnet = developer)
(Bytes < p75) OR (DstSubnet != servers) OR (SrcPortClass != registered) OR (SrcPortClass != dynamic)
(Bytes < p75) OR (DstSubnet != servers) OR (Duration <= p25) OR (SrcPortClass = registered) OR (SrcPortClass = dynamic)
(Bytes < p75) OR (DstSubnet != servers) OR (Packets < p75) OR (SrcPortClass = registered) OR (SrcPortClass = dynamic)
(Bytes < p75) OR (DstSubnet != servers) OR (SrcPortClass = well_known) OR (SrcPortClass = registered) OR (SrcPortClass = dynamic)
(Bytes < p75) OR (DstSubnet != servers) OR (SrcPortClass = registered) OR (SrcPortClass = dynamic) OR (SrcSubnet != developer)
(Bytes < p75) OR (DstSubnet != servers) OR (SrcPortClass = registered) OR (SrcPortClass = dynamic) OR (SrcSubnet = servers)
(Bytes <= p75) OR (Bytes > p50) OR (DstSubnet != servers)
(Bytes <= p75) OR (Bytes > p25) OR (DstSubnet != servers)
(Bytes <= p75) OR (Bytes >= p50) OR (DstSubnet != servers)
(Bytes <= p75) OR (Bytes >= p75) OR (DstSubnet != servers)
(Bytes <= p75) OR (DstSubnet != servers) OR (Packets > p25)
(Bytes <= p75) OR (DstPortClass != well_known) OR (DstSubnet != servers) OR (SrcSubnet != management)
(Bytes <= p75) OR (DstPortClass = http) OR (DstSubnet != servers) OR (SrcSubnet != management)
(Bytes <= p75) OR (DstSubnet != servers) OR (Duration > p25) OR (SrcSubnet != management)
(Bytes <= p75) OR (DstSubnet != servers) OR (Packets > p75) OR (SrcSubnet != management)
(Bytes <= p75) OR (DstSubnet != servers) OR (Packets >= p75) OR (SrcSubnet != management)
(Bytes <= p75) OR (DstSubnet != servers) OR (SrcPortClass != registered) OR (SrcSubnet != management)
(Bytes <= p75) OR (DstSubnet != servers) OR (SrcPortClass = dynamic) OR (SrcSubnet != management)
(Bytes <= p75) OR (DstSubnet != servers) OR (SrcSubnet != management) OR (SrcSubnet != developer)
(Bytes <= p75) OR (DstSubnet != servers) OR (Duration > p25) OR (SrcPortClass != registered)
(Bytes <= p75) OR (DstSubnet != servers) OR (Duration > p25) OR (SrcPortClass != dynamic)
(Bytes <= p75) OR (DstSubnet != servers) OR (Duration > p25) OR (SrcPortClass = well_known)
(Bytes <= p75) OR (DstSubnet != servers) OR (Duration > p25) OR (SrcSubnet != developer)
(Bytes <= p75) OR (DstSubnet != servers) OR (Duration > p25) OR (SrcSubnet = servers)
(Bytes <= p75) OR (DstSubnet != servers) OR (Duration <= p25) OR (Packets > p75)
(Bytes <= p75) OR (DstSubnet != servers) OR (Packets < p75) OR (Packets > p75)
(Bytes <= p75) OR (DstSubnet != servers) OR (Packets > p75) OR (SrcPortClass != registered)
(Bytes <= p75) OR (DstSubnet != servers) OR (Packets > p75) OR (SrcPortClass != dynamic)
(Bytes <= p75) OR (DstSubnet != servers) OR (Packets > p75) OR (SrcPortClass = well_known)
(Bytes <= p75) OR (DstSubnet != servers) OR (Packets > p75) OR (SrcSubnet != developer)
(Bytes <= p75) OR (DstSubnet != servers) OR (Packets > p75) OR (SrcSubnet = servers)
(Bytes <= p75) OR (DstSubnet != servers) OR (Duration <= p25) OR (Packets >= p75)
(Bytes <= p75) OR (DstSubnet != servers) OR (Packets >= p75) OR (SrcPortClass != registered)
(Bytes <= p75) OR (DstSubnet != servers) OR (Packets >= p75) OR (SrcPortClass != dynamic)
(Bytes <= p75) OR (DstSubnet != servers) OR (Packets >= p75) OR (SrcPortClass = well_known)
(Bytes <= p75) OR (DstSubnet != servers) OR (Packets >= p75) OR (SrcSubnet != developer)
(Bytes <= p75) OR (DstSubnet != servers) OR (Packets >= p75) OR (SrcSubnet = servers)
(Bytes <= p75) OR (DstSubnet != servers) OR (Packets >= p90) OR (SrcPortClass != registered)
(Bytes <= p75) OR (DstSubnet != servers) OR (Packets >= p90) OR (SrcSubnet != developer)
(Bytes <= p75) OR (DstPortClass != well_known) OR (DstSubnet != servers) OR (Duration <= p25) OR (Packets >= p90)
(Bytes <= p75) OR (DstPortClass = http) OR (DstSubnet != servers) OR (Duration <= p25) OR (Packets >= p90)
(Bytes <= p75) OR (DstSubnet != servers) OR (Duration <= p25) OR (Packets >= p90) OR (SrcPortClass = dynamic)
(Bytes <= p75) OR (DstSubnet != servers) OR (Duration <= p25) OR (Packets >= p90) OR (SrcSubnet = management)
(Bytes <= p75) OR (DstPortClass != well_known) OR (DstSubnet != servers) OR (Packets < p75) OR (Packets >= p90)
(Bytes <= p75) OR (DstPortClass = http) OR (DstSubnet != servers) OR (Packets < p75) OR (Packets >= p90)
(Bytes <= p75) OR (DstSubnet != servers) OR (Packets < p75) OR (Packets >= p90) OR (SrcPortClass = dynamic)
(Bytes <= p75) OR (DstSubnet != servers) OR (Packets < p75) OR (Packets >= p90) OR (SrcSubnet = management)
(Bytes <= p75) OR (DstPortClass != well_known) OR (DstSubnet != servers) OR (Packets >= p90) OR (SrcPortClass != dynamic)
(Bytes <= p75) OR (DstPortClass = http) OR (DstSubnet != servers) OR (Packets >= p90) OR (SrcPortClass != dynamic)
(Bytes <= p75) OR (DstSubnet != servers) OR (Packets >= p90) OR (SrcPortClass != dynamic) OR (SrcSubnet = management)
(Bytes <= p75) OR (DstPortClass != well_known) OR (DstSubnet != servers) OR (Packets >= p90) OR (SrcPortClass = well_known)
(Bytes <= p75) OR (DstPortClass = http) OR (DstSubnet != servers) OR (Packets >= p90) OR (SrcPortClass = well_known)
(Bytes <= p75) OR (DstSubnet != servers) OR (Packets >= p90) OR (SrcPortClass = well_known) OR (SrcPortClass = dynamic)
(Bytes <= p75) OR (DstSubnet != servers) OR (Packets >= p90) OR (SrcPortClass = well_known) OR (SrcSubnet = management)
(Bytes <= p75) OR (DstPortClass != well_known) OR (DstSubnet != servers) OR (Packets >= p90) OR (SrcSubnet = servers)
(Bytes <= p75) OR (DstPortClass = http) OR (DstSubnet != servers) OR (Packets >= p90) OR (SrcSubnet = servers)
(Bytes <= p75) OR (DstSubnet != servers) OR (Packets >= p90) OR (SrcPortClass = dynamic) OR (SrcSubnet = servers)
(Bytes <= p75) OR (DstSubnet != servers) OR (Packets >= p90) OR (SrcSubnet = servers) OR (SrcSubnet = management)
(Bytes <= p75) OR (DstSubnet != servers) OR (SrcPortClass != registered) OR (SrcSubnet = developer)
(Bytes <= p75) OR (DstPortClass != well_known) OR (DstSubnet != servers) OR (Duration <= p25) OR (SrcSubnet = developer)
(Bytes <= p75) OR (DstPortClass = http) OR (DstSubnet != servers) OR (Duration <= p25) OR (SrcSubnet = developer)
(Bytes <= p75) OR (DstSubnet != servers) OR (Duration <= p25) OR (SrcPortClass = dynamic) OR (SrcSubnet = developer)
(Bytes <= p75) OR (DstSubnet != servers) OR (Duration <= p25) OR (SrcSubnet = management) OR (SrcSubnet = developer)
(Bytes <= p75) OR (DstPortClass != well_known) OR (DstSubnet != servers) OR (SrcPortClass != dynamic) OR (SrcSubnet = developer)
(Bytes <= p75) OR (DstPortClass = http) OR (DstSubnet != servers) OR (SrcPortClass != dynamic) OR (SrcSubnet = developer)
(Bytes <= p75) OR (DstSubnet != servers) OR (SrcPortClass != dynamic) OR (SrcSubnet = management) OR (SrcSubnet = developer)
(Bytes <= p75) OR (DstPortClass != well_known) OR (DstSubnet != servers) OR (SrcPortClass = well_known) OR (SrcSubnet = developer)
(Bytes <= p75) OR (DstPortClass = http) OR (DstSubnet != servers) OR (SrcPortClass = well_known) OR (SrcSubnet = developer)
(Bytes <= p75) OR (DstSubnet != servers) OR (SrcPortClass = well_known) OR (SrcPortClass = dynamic) OR (SrcSubnet = developer)
(Bytes <= p75) OR (DstSubnet != servers) OR (SrcPortClass = well_known) OR (SrcSubnet = management) OR (SrcSubnet = developer)
(Bytes <= p75) OR (DstPortClass != well_known) OR (DstSubnet != servers) OR (SrcSubnet = servers) OR (SrcSubnet = developer)
(Bytes <= p75) OR (DstPortClass = http) OR (DstSubnet != servers) OR (SrcSubnet = servers) OR (SrcSubnet = developer)
(Bytes <= p75) OR (DstSubnet != servers) OR (SrcPortClass = dynamic) OR (SrcSubnet = servers) OR (SrcSubnet = developer)
(Bytes <= p75) OR (DstSubnet != servers) OR (SrcSubnet = servers) OR (SrcSubnet = management) OR (SrcSubnet = developer)
(Bytes <= p75) OR (DstSubnet != servers) OR (SrcPortClass != registered) OR (SrcPortClass != dynamic)
(Bytes <= p75) OR (DstSubnet != servers) OR (Duration <= p25) OR (SrcPortClass = registered) OR (SrcPortClass = dynamic)
(Bytes <= p75) OR (DstSubnet != servers) OR (Packets < p75) OR (SrcPortClass = registered) OR (SrcPortClass = dynamic)
(Bytes <= p75) OR (DstSubnet != servers) OR (SrcPortClass = well_known) OR (SrcPortClass = registered) OR (SrcPortClass = dynamic)
(Bytes <= p75) OR (DstSubnet != servers) OR (SrcPortClass = registered) OR (SrcPortClass = dynamic) OR (SrcSubnet != developer)
(Bytes <= p75) OR (DstSubnet != servers) OR (SrcPortClass = registered) OR (SrcPortClass = dynamic) OR (SrcSubnet = servers)
(Bytes > p50) OR (DstSubnet != servers) OR (Packets < p75)
(Bytes > p25) OR (DstSubnet != servers) OR (Packets < p75)
(Bytes >= p50) OR (DstSubnet != servers) OR (Packets < p75)
(DstSubnet != servers) OR (Duration > p25) OR (Packets < p75)
(DstSubnet != servers) OR (Packets < p75) OR (Packets > p25)
(Bytes > p75) OR (DstSubnet != servers) OR (Packets < p75) OR (SrcSubnet != management)
(Bytes >= p75) OR (DstSubnet != servers) OR (Packets < p75) OR (SrcSubnet != management)
(DstPortClass != well_known) OR (DstSubnet != servers) OR (Packets < p75) OR (SrcSubnet != management)
(DstPortClass = http) OR (DstSubnet != servers) OR (Packets < p75) OR (SrcSubnet != management)
(DstSubnet != servers) OR (Packets < p75) OR (Packets > p75) OR (SrcSubnet != management)
(DstSubnet != servers) OR (Packets < p75) OR (SrcPortClass != registered) OR (SrcSubnet != management)
(DstSubnet != servers) OR (Packets < p75) OR (SrcPortClass = dynamic) OR (SrcSubnet != management)
(DstSubnet != servers) OR (Packets < p75) OR (SrcSubnet != management) OR (SrcSubnet != developer)
(Bytes > p75) OR (DstSubnet != servers) OR (Packets < p75) OR (SrcSubnet = developer)
(Bytes >= p75) OR (DstSubnet != servers) OR (Packets < p75) OR (SrcSubnet = developer)
(DstPortClass != well_known) OR (DstSubnet != servers) OR (Packets < p75) OR (SrcSubnet = developer)
(DstPortClass = http) OR (DstSubnet != servers) OR (Packets < p75) OR (SrcSubnet = developer)
(DstSubnet != servers) OR (Packets < p75) OR (Packets > p75) OR (SrcSubnet = developer)
(DstSubnet != servers) OR (Packets < p75) OR (SrcPortClass != registered) OR (SrcSubnet = developer)
(DstSubnet != servers) OR (Packets < p75) OR (SrcPortClass = dynamic) OR (SrcSubnet = developer)
(DstSubnet != servers) OR (Packets < p75) OR (SrcSubnet = management) OR (SrcSubnet = developer)
(Bytes > p75) OR (DstSubnet != servers) OR (Duration > p75) OR (Packets < p75) OR (SrcPortClass != dynamic)
(Bytes > p75) OR (DstSubnet != servers) OR (Duration > p75) OR (Packets < p75) OR (SrcPortClass = registered)
(Bytes > p75) OR (DstSubnet != servers) OR (Duration > p90) OR (Packets < p75) OR (SrcPortClass != dynamic)
(Bytes > p75) OR (DstSubnet != servers) OR (Duration > p90) OR (Packets < p75) OR (SrcPortClass = registered)
(Bytes > p75) OR (DstSubnet != servers) OR (Duration >= p75) OR (Packets < p75) OR (SrcPortClass != dynamic)
(Bytes > p75) OR (DstSubnet != servers) OR (Duration >= p75) OR (Packets < p75) OR (SrcPortClass = registered)
(Bytes > p75) OR (DstSubnet != servers) OR (Duration >= p90) OR (Packets < p75) OR (SrcPortClass != dynamic)
(Bytes > p75) OR (DstSubnet != servers) OR (Duration >= p90) OR (Packets < p75) OR (SrcPortClass = registered)
(Bytes > p75) OR (DstSubnet != servers) OR (Packets < p75) OR (SrcPortClass != registered) OR (SrcPortClass != dynamic)
(Bytes > p75) OR (DstSubnet != servers) OR (Packets < p75) OR (SrcPortClass = registered) OR (SrcPortClass = dynamic)
(Bytes >= p75) OR (DstSubnet != servers) OR (Duration > p75) OR (Packets < p75) OR (SrcPortClass != dynamic)
(Bytes >= p75) OR (DstSubnet != servers) OR (Duration > p75) OR (Packets < p75) OR (SrcPortClass = registered)
(Bytes >= p75) OR (DstSubnet != servers) OR (Duration > p90) OR (Packets < p75) OR (SrcPortClass != dynamic)
(Bytes >= p75) OR (DstSubnet != servers) OR (Duration > p90) OR (Packets < p75) OR (SrcPortClass = registered)
(Bytes >= p75) OR (DstSubnet != servers) OR (Duration >= p75) OR (Packets < p75) OR (SrcPortClass != dynamic)
(Bytes >= p75) OR (DstSubnet != servers) OR (Duration >= p75) OR (Packets < p75) OR (SrcPortClass = registered)
(Bytes >= p75) OR (DstSubnet != servers) OR (Duration >= p90) OR (Packets < p75) OR (SrcPortClass != dynamic)
(Bytes >= p75) OR (DstSubnet != servers) OR (Duration >= p90) OR (Packets < p75) OR (SrcPortClass = registered)
(Bytes >= p75) OR (DstSubnet != servers) OR (Packets < p75) OR (SrcPortClass != registered) OR (SrcPortClass != dynamic)
(Bytes >= p75) OR (DstSubnet != servers) OR (Packets < p75) OR (SrcPortClass = registered) OR (SrcPortClass = dynamic)
(DstSubnet != servers) OR (Duration > p75) OR (Packets < p75) OR (Packets > p75) OR (SrcPortClass != dynamic)
(DstSubnet != servers) OR (Duration > p75) OR (Packets < p75) OR (Packets > p75) OR (SrcPortClass = registered)
(DstSubnet != servers) OR (Duration > p90) OR (Packets < p75) OR (Packets > p75) OR (SrcPortClass != dynamic)
(DstSubnet != servers) OR (Duration > p90) OR (Packets < p75) OR (Packets > p75) OR (SrcPortClass = registered)
(DstSubnet != servers) OR (Duration >= p75) OR (Packets < p75) OR (Packets > p75) OR (SrcPortClass != dynamic)
(DstSubnet != servers) OR (Duration >= p75) OR (Packets < p75) OR (Packets > p75) OR (SrcPortClass = registered)
(DstSubnet != servers) OR (Duration >= p90) OR (Packets < p75) OR (Packets > p75) OR (SrcPortClass != dynamic)